# Tutorial 03: BlueSky API
Author: Georg Ahnert

In this notebook, we will learn how to access data on the web through **API requests**.

This is different from _webscraping_, which we had a look at in the previous tutorials, since APIs provide data in a structured format.

However, APIs might not always be available or well-documented.

In this tutorial, we will focus on the [BlueSky (ATProto) API](https://docs.bsky.app/).

In [ ]:
# Install dependencies
!pip install requests pandas atproto tqdm ipywidgets

## REST API Basics

_APIs_ (Application Programming Interfaces) are aggreed upon standards that allows us (_clients_) to talk to a _server_ and request information from it, or provide it with information.
_REST_ (Representational State Transfer) describes a de-facto standard that many APIs on the web adhere to.

A central concept in REST APIs are _resources_. Each resource that we might want to interact with has a unique address, known as a _URI_ (Uniform Resource Identifier).

Different resources support different _HTTP methods_ or actions that you can perform on them.
The main HTTP methods are:

| HTTP method | action | description |
|---|---|---|
| GET	| Read | Retrieve data from the server |
| POST | Create | Send new data to the server to create a resource |
| PUT | Update | Replace an existing resource entirely |
| DELETE | Delete | Remove a resource from the server |

These methods are performed on dedicated _endpoints_ that support different types of interactions.
For example: https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile

You can directly try this out, simply by opening the endpoint above in your browser. By default, a GET request is performed.

We can also use a dedicated program like [Postman](https://www.postman.com/) to try out different types of requests. This makes it a bit easier to add parameters to a request or to use different HTTP methods.

Or you can use the requests package in Python. Let's try that out:

In [ ]:
import requests
import pandas as pd

In [3]:
url = "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile"
response = requests.get(url) # if you remember from exercise 1, we had actually already used this to GET a webpage

The server response is now stored in the `response` variable and contains a lot of meta-information as well:

In [4]:
dict(response.headers)

{'Date': 'Tue, 03 Mar 2026 18:06:52 GMT',
 'Content-Type': 'application/json; charset=utf-8',
 'Content-Length': '85',
 'Connection': 'keep-alive',
 'Server': 'BunnyCDN-DE1-1330',
 'CDN-PullZone': '1816608',
 'CDN-RequestCountryCode': 'DE',
 'Access-Control-Allow-Origin': '*',
 'Cache-Control': 'public, max-age=5',
 'X-Powered-By': 'Express',
 'Strict-Transport-Security': 'max-age=63072000',
 'CDN-ProxyVer': '1.47',
 'CDN-RequestPullSuccess': 'True',
 'CDN-RequestPullCode': '400',
 'CDN-CachedAt': '03/03/2026 18:06:52',
 'CDN-EdgeStorageId': '1332',
 'CDN-RequestId': '9af31603395aefab9d9a207a2ec68861',
 'CDN-Cache': 'EXPIRED',
 'CDN-Status': '400',
 'CDN-RequestTime': '0'}

One of the most important pieces of information is the [HTTP status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). It tells us if our request was successful or not.

The most common status codes are:

| Status Code | Status Text | Category | Description |
| :--- | :--- | :--- | :--- |
| **200** | OK | Success | The request was successful and the server sent data back. |
| **201** | Created | Success | The request was successful and a new resource was created. |
| **204** | No Content | Success | The request was successful, but there is no data to return. |
| **400** | Bad Request | Client Error | The server cannot process the request due to a client error. |
| **401** | Unauthorized | Client Error | Authentication is required and has failed or hasn't been provided. |
| **403** | Forbidden | Client Error | The server understood the request but refuses to authorize it. |
| **404** | Not Found | Client Error | The requested resource could not be found on the server. |
| **429** | Too Many Requests | Client Error | The user has sent too many requests in a given amount of time. |
| **500** | Internal Server Error | Server Error | A generic error message when the server encounters an unexpected condition. |
| **503** | Service Unavailable | Server Error | The server is currently unable to handle the request (overloaded/down). |

In [5]:
response.status_code # meh, Bad Request

400

Finally, let's have a look at the actual response that we got from the server on our GET request.

We can see that the server returned a JSON (JavaScript Object Notation) object that can be automatically converted into a Python dictionary.

In [6]:
response.text

'{"error":"InvalidRequest","message":"Error: Params must have the property \\"actor\\""}'

In [7]:
response.json()

{'error': 'InvalidRequest',
 'message': 'Error: Params must have the property "actor"'}

## Parameters in HTTP Requests

Okay, seems like we didn't use the BlueSky API properly and forgot to specify which profile we want to GET. Let's fix that:

In [8]:
url = "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile"
params = {
    'actor': 'xkcd.com'
}

response = requests.get(url, params=params)
response.json()

{'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
 'handle': 'xkcd.com',
 'displayName': 'Randall Munroe',
 'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
 'associated': {'lists': 0,
  'feedgens': 0,
  'starterPacks': 0,
  'labeler': False,
  'chat': {'allowIncoming': 'following'},
  'activitySubscription': {'allowSubscriptions': 'followers'}},
 'labels': [],
 'createdAt': '2023-04-27T20:54:28.631Z',
 'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
    'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
    'isValid': True,
    'createdAt': '2025-04-21T10:47:23.196Z'}],
  'verifiedStatus': 'valid',
  'trustedVerifierStatus': 'none'},
 'indexedAt': '2024-01-20T05:04:56.709Z',
 'followersCount': 462977,
 'followsCount': 26,
 'postsCount': 581}

Maybe the most recent posts are a bit more interesting:

In [9]:
url = "https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed"
params = {
    # see the documentation for possible parameters: https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed
    'actor': 'xkcd.com',
    'limit': 10,
}

response = requests.get(url, params=params)
response.json()

{'feed': [{'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mg46hoty222r',
    'cid': 'bafyreic4fc27vtnutxr4t6ditdjudjdkkmhoycozmqcqaoggjqeg6lj2z4',
    'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
     'handle': 'xkcd.com',
     'displayName': 'Randall Munroe',
     'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
     'associated': {'chat': {'allowIncoming': 'following'},
      'activitySubscription': {'allowSubscriptions': 'followers'}},
     'labels': [],
     'createdAt': '2023-04-27T20:54:28.631Z',
     'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
        'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
        'isValid': True,
        'createdAt': '2025-04-21T10:47:23.196Z'}],
      'verifiedStatus': 'valid',
      'trustedVerifierStatus': 'none'}},
    'record': {'$type': 'app.bsky.feed.post',
     'createdAt': '2026-03-02T21:16:56.446Z',
     'embed': {'$type': 'app.bsky.embed.images',
      'images': [{'alt': 'Comic. PERSON 1: I got 10,000 amp service and put each outlet on its own 500 amp breaker, so I never have to worry about overloading a circuit again! PERSON 2 with ponytail: Clever. PERSON 1: Oh, that reminds me–Do you know where to buy cords that don’t catch fire? ',
        'aspectRatio': {'height': 820, 'width': 597},
        'image': {'$type': 'blob',
         'ref': {'$link': 'bafkreiaihs3xex55teffdghemiw5be6redq4r4jrpo6d6fo3babzrpgmhe'},
         'mimeType': 'image/jpeg',
         'size': 140507}}]},
     'facets': [{'features': [{'$type': 'app.bsky.richtext.facet#link',
         'uri': 'https://xkcd.com/3211/'}],
       'index': {'byteEnd': 24, 'byteStart': 10}}],
     'langs': ['en'],
     'text': 'Amperage\n\nxkcd.com/3211/'},
    'embed': {'$type': 'app.bsky.embed.images#view',
     'images': [{'thumb': 'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreiaihs3xex55teffdghemiw5be6redq4r4jrpo6d6fo3babzrpgmhe@jpeg',
       'fullsize': 'https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreiaihs3xex55teffdghemiw5be6redq4r4jrpo6d6fo3babzrpgmhe@jpeg',
       'alt': 'Comic. PERSON 1: I got 10,000 amp service and put each outlet on its own 500 amp breaker, so I never have to worry about overloading a circuit again! PERSON 2 with ponytail: Clever. PERSON 1: Oh, that reminds me–Do you know where to buy cords that don’t catch fire? ',
       'aspectRatio': {'height': 820, 'width': 597}}]},
    'bookmarkCount': 18,
    'replyCount': 32,
    'repostCount': 209,
    'likeCount': 2292,
    'quoteCount': 30,
    'indexedAt': '2026-03-02T21:16:37.767Z',
    'labels': []}},
  {'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mfpmbfjacs2q',
    'cid': 'bafyreicnh3zwl2gktuiaq55n6j7t6dom35y5hpzvnqpyw34sccal7yjarm',
    'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
     'handle': 'xkcd.com',
     'displayName': 'Randall Munroe',
     'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
     'associated': {'chat': {'allowIncoming': 'following'},
      'activitySubscription': {'allowSubscriptions': 'followers'}},
     'labels': [],
     'createdAt': '2023-04-27T20:54:28.631Z',
     'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
        'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
        'isValid': True,
        'createdAt': '2025-04-21T10:47:23.196Z'}],
      'verifiedStatus': 'valid',
      'trustedVerifierStatus': 'none'}},
    'record': {'$type': 'app.bsky.feed.post',
     'createdAt': '2026-02-25T21:19:21.117Z',
     'embed': {'$type': 'app.bsky.embed.images',
      'images': [{'alt': '4-panel comic. (1) [Person with white hat talking to another person.] PERSON 1 with white hat: As Sherlock Holmes said, When you have eliminated the impossible, whatever remains, however improbable, must be the truth. (2) PERSON 2: What about the possibility that you forgot to eliminate a possibility? Or that you eliminated one incorrectly? Both of those remain, too. (3) PERSON 1: You’re being pedantic. It’s just a general rule for deduction. PERSON 2: But it’s a *bad rule*. (4) PERSON 2: How often have you thought, “I can’t find this thing, and I’ve searched the whole house. The only place I haven’t looked is the car, so it *must* be there.” PERSON 2: ...And then it’s never in the car. PERSON 1: *It’s never in the car!*',
        'aspectRatio': {'height': 698, 'width': 1350},
        'image': {'$type': 'blob',
         'ref': {'$link': 'bafkreifiy7vve3vnzcdv2ptjmuvd3twrsyuu2s5tkyvonqzk56mvinoxae'},
         'mimeType': 'image/jpeg',
         'size': 321453}}]},
     'facets': [{'features': [{'$type': 'app.bsky.richtext.facet#link',
         'uri': 'https://xkcd.com/3210/'}],
       'index': {'byteEnd': 42, 'byteStart': 28}}],
     'langs': ['en'],
     'text': 'Eliminating the Impossible\n\nxkcd.com/3210/'},
    'embed': {'$type': 'app.bsky.embed.images#view',
     'images': [{'thumb': 'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreifiy7vve3vnzcdv2ptjmuvd3twrsyuu2s5tkyvonqzk56mvinoxae@jpeg',
       'fullsize': 'https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreifiy7vve3vnzcdv2ptjmuvd3twrsyuu2s5tkyvonqzk56mvinoxae@jpeg',
       'alt': '4-panel comic. (1) [Person with white hat talking to another person.] PERSON 1 with white hat: As Sherlock Holmes said, When you have eliminated the impossible, whatever remains, however improbable, must be the truth. (2) PERSON 2: What about the possibility that you forgot to eliminate a possibility? Or that you eliminated one incorrectly? Both of those remain, too. (3) PERSON 1: You’re being pedantic. It’s just a general rule for deduction. PERSON 2: But it’s a *bad rule*. (4) PERSON 2: How often have you thought, “I can’t find this thing, and I’ve searched the whole house. The only place I haven’t looked is the car, so it *must* be there.” PERSON 2: ...And then it’s never in the car. PERSON 1: *It’s never in the car!*',
       'aspectRatio': {'height': 698, 'width': 1350}}]},
    'bookmarkCount': 35,
    'replyCount': 38,
    'repostCount': 455,
    'likeCount': 2816,
    'quoteCount': 24,
    'indexedAt': '2026-02-25T21:19:12.249Z',
    'labels': []}},
  {'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mfmz6mihks2p',
    'cid': 'bafyreihva22x4yenq3euvkgaudrjcahbvez6d6mtogasqt2vt6cocfjh4e',
    'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
     'handle': 'xkcd.com',
     'displayName': 'Randall Munroe',
     'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
     'associated': {'chat': {'allowIncoming': 'following'},
      'activitySubscription': {'allowSubscriptions': 'followers'}},
     'labels': [],
     'createdAt': '2023-04-27T20:54:28.631Z',
     'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
        'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
        'isValid': True,
        'createdAt': '2025-04-21T10:47:23.196Z'}],
      'verifiedStatus': 'valid',
      'trustedVerifierStatus': 'none'}},
    'record': {'$type': 'app.bsky.feed.post',
     'createdAt': '2026-02-24T20:32:27.198Z',
     'embed': {'$type': 'app.bsky.embed.images',
      'images': [{'alt': 'Comic. [Person is sitting at a desk with a laptop, turned toward voice coming from off-panel.] VOICE FROM OFF-PANEL: I got you the ingredients for dinner tonight. Oh, and the plums in the fridge drawer are for my yogurt tomorrow; you should just leave them. Be back later! PERSON’S THOUGHT BUBBLE: Oh no. [caption] Help. It actually happened. I shouldn’t. But how can I not!?',
        'aspectRatio': {'height': 817, 'width': 502},
        'image': {'$type': 'blob',
         'ref': {'$link': 'bafkreigse57u6yvi5or4mnvpm5jbn3y3kzbxyzypmjmhbu7spcn6fe4wtm'},
         'mimeType': 'image/jpeg',
         'size': 135078}}]},
     'facets': [{'features': [{'$type': 'app.bsky.richtext.facet#link',
         'uri': 'https://xkcd.com/3209/'}],
       'index': {'byteEnd': 21, 'byteStart': 7}}],
     'langs': ['en'],
     'text': 'Plums\n\nxkcd.com/3209/'},
    'embed': {'$type': 'app.bsky.embed.images#view',
     'images': [{'thumb': 'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreigse57u6yvi5or4mnvpm5jbn3y3kzbxyzypmjmhbu7spcn6fe4wtm@jpeg',
       'fullsize': 'https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreigse57u6yvi5or4mnvpm5jbn3y3kzbxyzypmjmhbu7spcn6fe4wtm@jpeg',
       'alt': 'Comic. [Person is sitting at a desk with a laptop, turned toward voice coming from off-panel.] VOICE FROM OFF-PANEL: I got you the ingredients for dinner tonight. Oh, and the plums in the fridge drawer are for my yogurt tomorrow; you should just leave them. Be back later! PERSON’S THOUGHT BUBBLE: Oh no. [caption] Help. It actually happened. I shouldn’t. But how can I not!?',
       'aspectRatio': {'height': 817, 'width': 502}}]},
    'bookmarkCount': 27,
    'replyCount': 45,
    'repostCount': 429,
    'likeCount': 2720,
    'quoteCount': 38,
    'indexedAt': '2026-02-24T20:32:17.952Z',
    'labels': []}},
  {'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mf3mefypik27',
    'cid': 'bafyreiczt4xonmevxohl3ii6krdmlshmssaxkpl6o2eod7ekioye5bvd24',
    'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
     'handle': 'xkcd.com',
     'displayName': 'Randall Munroe',
     'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
     'associated': {'chat': {'allowIncoming': 'following'},
      'activitySubscription': {'allowSubscriptions': 'followers'}},
     'labels': [],
     'createdAt': '2023-04-27T20:54:28.631Z',
     'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
        'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
        'isValid': True,
        'createdAt': '2025-04-21T10:47:23.196Z'}],
      'verifiedStatus': 'valid',
      'trustedVerifierStatus': 'none'}},
    'record': {'$type': 'app.bsky.feed.post',
     'createdAt': '2026-02-17T22:27:47.519Z',
     'embed': {'$type': 'app.bsky.embed.images',
      'images': [{'alt': '4-panel comic. (1) [Two people in a room with bed and nightstand. One person points at something on ceiling.] PERSON 1 with short hair on top of head: What’s that device? PERSON 2 with ponytail: Part of the supernova early warning system. There hasn’t been a Milky Way supernova in over a century. Astronomers don’t want to miss the next one. (2) [Person 2 sits on bed.] PERSON 2: 20 years ago, we set up a supernova alert system using neutrino detectors. It should give us a few hours’ advance notice. (3) PERSON 2: If it ever goes off, every astronomer on Earth will scramble to point their equipment at the sky. PERSON 1: Oh, Ok. So is that a detector? Or some kind of telescope? (4) PERSON 2 [leaving]: Fireworks launcher. I *refuse* to sleep through a supernova. PERSON 1: I think I’ll spend the night at my place instead.  ',
        'aspectRatio': {'height': 641, 'width': 1480},
        'image': {'$type': 'blob',
         'ref': {'$link': 'bafkreieib3sjwqtdeaedpuit6ewx4mm56j3nzcvfqpwbtzifnvsvtp6rde'},
         'mimeType': 'image/jpeg',
         'size': 356394}}]},
     'facets': [{'features': [{'$type': 'app.bsky.richtext.facet#link',
         'uri': 'https://xkcd.com/3208/'}],
       'index': {'byteEnd': 21, 'byteStart': 7}}],
     'langs': ['en'],
     'text': 'SNEWS\n\nxkcd.com/3208/'},
    'embed': {'$type': 'app.bsky.embed.images#view',
     'images': [{'thumb': 'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreieib3sjwqtdeaedpuit6ewx4mm56j3nzcvfqpwbtzifnvsvtp6rde@jpeg',
       'fullsize': 'https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreieib3sjwqtdeaedpuit6ewx4mm56j3nzcvfqpwbtzifnvsvtp6rde@jpeg',
       'alt': '4-panel comic. (1) [Two people in a room with bed and nightstand. One person points at something on ceiling.] PERSON 1 with short hair on top of head: What’s that device? PERSON 2 with ponytail: Part of the supernova early warning system. There hasn’t been a Milky Way supernova in over a century. Astronomers don’t want to miss the next one. (2) [Person 2 sits on bed.] PERSON 2: 20 years ago, we set up a supernova alert system using neutrino detectors. It should give us a few hours’ advance notice. (3) PERSON 2: If it ever goes off, every astronomer on Earth will scramble to point their equipment at the sky. PERSON 1: Oh, Ok. So is that a detector? Or some kind of telescope? (4) PERSON 2 [leaving]: Fireworks launcher. I *refuse* to sleep through a supernova. PERSON 1: I think I’ll spend the night at my place instead.  ',
       'aspectRatio': {'height': 641, 'width': 1480}}]},
    'bookmarkCount': 10,
    'replyCount': 20,
    'repostCount': 193,
    'likeCount': 1987,
    'quoteCount': 17,
    'indexedAt': '2026-02-17T22:27:50.055Z',
    'labels': []}},
  {'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3meyulbztgc22',
    'cid': 'bafyreihpzg2htj6tsdfj3i6zkxxtwm7sbp64jchmhubjdlc5ij2ug4m7sy',
    'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
     'handle': 'xkcd.com',
     'displayName': 'Randall Munroe',
     'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
     'associated': {'chat': {'allowIncoming': 'following'},
      'activitySubscription': {'allowSubscriptions': 'followers'}},
     'labels': [],
     'createdAt': '2023-04-27T20:54:28.631Z',
     'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
        'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
        'isValid': True,
        'createdAt': '2025-04-21T10:47:23.196Z'}],
      'verifiedStatus': 'valid',
      'trustedVerifierStatus': 'none'}},
    'record': {'$type': 'app.bsky.feed.post',
     'createdAt': '2026-02-16T20:16:48.963Z',
     'embed': {'$type': 'app.bsky.embed.images',
      'images': [{'alt': 'Comic. Bad Map Projection #216: Zero Declination. A cylindrical projection distorted so that up is *magnetic* north. Distorted map with red arrows around the edges pointing different directions. ',
        'aspectRatio': {'height': 1088, 'width': 1480},
        'image': {'$type': 'blob',
         'ref': {'$link': 'bafkreictjahzj6t3u2cl5xauvnvn4hkioa4hfanaiybzshhzmueka4gysq'},
         'mimeType': 'image/jpeg',
         'size': 434665}}]},
     'facets': [{'features': [{'$type': 'app.bsky.richtext.facet#link',
         'uri': 'https://xkcd.com/3207/'}],
       'index': {'byteEnd': 52, 'byteStart': 38}}],
     'langs': ['en'],
     'text': 'Bad Map Projection: Zero Declination\n\nxkcd.com/3207/'},
    'embed': {'$type': 'app.bsky.embed.images#view',
     'images': [{'thumb': 'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreictjahzj6t3u2cl5xauvnvn4hkioa4hfanaiybzshhzmueka4gysq@jpeg',
       'fullsize': 'https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreictjahzj6t3u2cl5xauvnvn4hkioa4hfanaiybzshhzmueka4gysq@jpeg',
       'alt': 'Comic. Bad Map Projection #216: Zero Declination. A cylindrical projection distorted so that up is *magnetic* north. Distorted map with red arrows around the edges pointing different directions. ',
       'aspectRatio': {'height': 1088, 'width': 1480}}]},
    'bookmarkCount': 19,
    'replyCount': 20,
    'repostCount': 143,
    'likeCount': 1562,
    'quoteCount': 9,
    'indexedAt': '2026-02-16T20:16:52.253Z',
    'labels': []}},
  {'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3metxtlr4bk2x',
    'cid': 'bafyreicn2rep3u3agd3gljmxar472pjzm6l64fd3uu6o4tw6kv4vtlf4nu',
    'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
     'handle': 'xkcd.com',
     'displayName': 'Randall Munroe',
     'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
     'associated': {'chat': {'allowIncoming': 'following'},
      'activitySubscription': {'allowSubscriptions': 'followers'}},
     'labels': [],
     'createdAt': '2023-04-27T20:54:28.631Z',
     'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
        'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
        'isValid': True,
        'createdAt': '2025-04-21T10:47:23.196Z'}],
      'verifiedStatus': 'valid',
      'trustedVerifierStatus': 'none'}},
    'record': {'$type': 'app.bsky.feed.post',
     'createdAt': '2026-02-14T21:31:50.130Z',
     'embed': {'$type': 'app.bsky.embed.images',
      'images': [{'alt': '4-panel comic. (1) [Person 1 unrolls carpet outdoors while Person 2 with short hair pulls cart full of more rolls.] (2) [Continuing uphill.] (3) [After going over a bump that takes them downhill, both people catch carpet roll that’s falling off the cart.] (4) PERSON 2: You’re *sure* we started installing the wall-to-wall carpet on the right side of the wall? PERSON 1: The other end of the room *must* be getting close by now. ',
        'aspectRatio': {'height': 544, 'width': 1480},
        'image': {'$type': 'blob',
         'ref': {'$link': 'bafkreidkiho4gmby5jfeiyub7tc6rx7r2hyqz5e6iizh3fzfhlon3d5fi4'},
         'mimeType': 'image/jpeg',
         'size': 181045}}]},
     'facets': [{'features': [{'$type': 'app.bsky.richtext.facet#link',
         'uri': 'https://xkcd.com/3206/'}],
       'index': {'byteEnd': 28, 'byteStart': 14}}],
     'langs': ['en'],
     'text': 'Installation\n\nxkcd.com/3206/'},
    'embed': {'$type': 'app.bsky.embed.images#view',
     'images': [{'thumb': 'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreidkiho4gmby5jfeiyub7tc6rx7r2hyqz5e6iizh3fzfhlon3d5fi4@jpeg',
       'fullsize': 'https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreidkiho4gmby5jfeiyub7tc6rx7r2hyqz5e6iizh3fzfhlon3d5fi4@jpeg',
       'alt': '4-panel comic. (1) [Person 1 unrolls carpet outdoors while Person 2 with short hair pulls cart full of more rolls.] (2) [Continuing uphill.] (3) [After going over a bump that takes them downhill, both people catch carpet roll that’s falling off the cart.] (4) PERSON 2: You’re *sure* we started installing the wall-to-wall carpet on the right side of the wall? PERSON 1: The other end of the room *must* be getting close by now. ',
       'aspectRatio': {'height': 544, 'width': 1480}}]},
    'bookmarkCount': 12,
    'replyCount': 22,
    'repostCount': 230,
    'likeCount': 2527,
    'quoteCount': 6,
    'indexedAt': '2026-02-14T21:31:51.853Z',
    'labels': []}},
  {'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3memdoaun4k2s',
    'cid': 'bafyreihtb7ryxvvxsizvnclzerdktlepubdrgdhepb74xgnge7yklhvuba',
    'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
     'handle': 'xkcd.com',
     'displayName': 'Randall Munroe',
     'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
     'associated': {'chat': {'allowIncoming': 'following'},
      'activitySubscription': {'allowSubscriptions': 'followers'}},
     'labels': [],
     'createdAt': '2023-04-27T20:54:28.631Z',

In [10]:
# Inspecting the first post in the authorFeed a bit further
posts = response.json()['feed']
posts[0]

{'post': {'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mg46hoty222r',
  'cid': 'bafyreic4fc27vtnutxr4t6ditdjudjdkkmhoycozmqcqaoggjqeg6lj2z4',
  'author': {'did': 'did:plc:cz73r7iyiqn26upot4jtjdhk',
   'handle': 'xkcd.com',
   'displayName': 'Randall Munroe',
   'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreibandvfr3i2qpwbuzfwcw26px2wfh2vkrgtbr2neiof4muzca2h2i@jpeg',
   'associated': {'chat': {'allowIncoming': 'following'},
    'activitySubscription': {'allowSubscriptions': 'followers'}},
   'labels': [],
   'createdAt': '2023-04-27T20:54:28.631Z',
   'verification': {'verifications': [{'issuer': 'did:plc:z72i7hdynmk6r22z27h6tvur',
      'uri': 'at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3lndpuy2nfk2z',
      'isValid': True,
      'createdAt': '2025-04-21T10:47:23.196Z'}],
    'verifiedStatus': 'valid',
    'trustedVerifierStatus': 'none'}},
  'record': {'$type': 'app.bsky.feed.post',
   'createdAt': '2026-03-02T21:16:56.446Z',
   'embed': {'$type': 'app.bsky.embed.images',
    'images': [{'alt': 'Comic. PERSON 1: I got 10,000 amp service and put each outlet on its own 500 amp breaker, so I never have to worry about overloading a circuit again! PERSON 2 with ponytail: Clever. PERSON 1: Oh, that reminds me–Do you know where to buy cords that don’t catch fire? ',
      'aspectRatio': {'height': 820, 'width': 597},
      'image': {'$type': 'blob',
       'ref': {'$link': 'bafkreiaihs3xex55teffdghemiw5be6redq4r4jrpo6d6fo3babzrpgmhe'},
       'mimeType': 'image/jpeg',
       'size': 140507}}]},
   'facets': [{'features': [{'$type': 'app.bsky.richtext.facet#link',
       'uri': 'https://xkcd.com/3211/'}],
     'index': {'byteEnd': 24, 'byteStart': 10}}],
   'langs': ['en'],
   'text': 'Amperage\n\nxkcd.com/3211/'},
  'embed': {'$type': 'app.bsky.embed.images#view',
   'images': [{'thumb': 'https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreiaihs3xex55teffdghemiw5be6redq4r4jrpo6d6fo3babzrpgmhe@jpeg',
     'fullsize': 'https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:cz73r7iyiqn26upot4jtjdhk/bafkreiaihs3xex55teffdghemiw5be6redq4r4jrpo6d6fo3babzrpgmhe@jpeg',
     'alt': 'Comic. PERSON 1: I got 10,000 amp service and put each outlet on its own 500 amp breaker, so I never have to worry about overloading a circuit again! PERSON 2 with ponytail: Clever. PERSON 1: Oh, that reminds me–Do you know where to buy cords that don’t catch fire? ',
     'aspectRatio': {'height': 820, 'width': 597}}]},
  'bookmarkCount': 18,
  'replyCount': 32,
  'repostCount': 209,
  'likeCount': 2292,
  'quoteCount': 30,
  'indexedAt': '2026-03-02T21:16:37.767Z',
  'labels': []}}

Based on the URI of this first post, we can investigate who liked it:

In [11]:
url = "https://public.api.bsky.app/xrpc/app.bsky.feed.getLikes"
params = {
    'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mg46hoty222r',
}

response = requests.get(url, params=params)
response.json()

{'likes': [{'actor': {'did': 'did:plc:wb3tevjffxyws4dh6mkoitc4',
    'handle': 'pulsargig.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:wb3tevjffxyws4dh6mkoitc4/bafkreigt342zzmmaq3hs4uuhrjlhd5n3fzrdniltklryya5p24ea2xwkge@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-22T03:53:35.853Z',
    'indexedAt': '2024-11-22T03:53:35.853Z'},
   'createdAt': '2026-03-03T18:05:51.153Z',
   'indexedAt': '2026-03-03T18:05:51.153Z'},
  {'actor': {'did': 'did:plc:fc3t6zpdthu7bgbrne3g4krg',
    'handle': 'sisyphianspartacus.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:fc3t6zpdthu7bgbrne3g4krg/bafkreic2u2tibbixdwuzlqxhtmijhec2kzh3jws32mm3zxsuitujredcme@jpeg',
    'associated': {'chat': {'allowIncoming': 'none'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2025-03-10T14:32:06.642Z',
    'indexedAt': '2025-05-04T22:32:03.275Z'},
   'createdAt': '2026-03-03T18:04:47.877Z',
   'indexedAt': '2026-03-03T18:04:47.877Z'},
  {'actor': {'did': 'did:plc:325f7xemyvavdxkkvbi67um6',
    'handle': '1condor12.bsky.social',
    'displayName': 'Steelperigren',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2023-08-30T03:19:26.358Z',
    'description': 'He/him | 30 years old\nConsummate lurker',
    'indexedAt': '2024-01-20T06:38:12.379Z'},
   'createdAt': '2026-03-03T18:01:49.868Z',
   'indexedAt': '2026-03-03T18:01:49.259Z'},
  {'actor': {'did': 'did:plc:4xn7om7w4ys7eorunku7n3w4',
    'handle': 'jjjennnnn.com',
    'displayName': 'JJJENNNNN',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:4xn7om7w4ys7eorunku7n3w4/bafkreibzyt2jsibz7u7xs3kg7oidsl5mptk2y3kg2l5hoizfccj5wbhwoq@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-10-27T20:30:04.109Z',
    'description': '🤔 - Jʼen doute.\n\n🇨🇦 in 🇺🇸',
    'indexedAt': '2025-05-10T20:15:16.540Z'},
   'createdAt': '2026-03-03T18:00:26.061Z',
   'indexedAt': '2026-03-03T18:00:26.061Z'},
  {'actor': {'did': 'did:plc:usfbknt6ptd7nqaihbhdcikc',
    'handle': 'ouromakesgames.bsky.social',
    'displayName': 'Ouroboros',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:usfbknt6ptd7nqaihbhdcikc/bafkreicwcx7cluradw7ryqjowgsd6n2vhk7nztsmp7p4qqoe3w22o2gkg4@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-14T00:26:48.277Z',
    'description': 'What if we placed our Github repositories next to each other...?\n🇨🇦',
    'indexedAt': '2026-01-31T23:12:12.346Z'},
   'createdAt': '2026-03-03T17:55:37.882Z',
   'indexedAt': '2026-03-03T17:55:37.882Z'},
  {'actor': {'did': 'did:plc:ysxhfdhksecz64m2mon3ctxs',
    'handle': 'krikalitika.bsky.social',
    'displayName': 'Turing Pest',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:ysxhfdhksecz64m2mon3ctxs/bafkreieko6arzmyhipbmf2lwbpdss3bdtszkqqwsjljgqshkeklcteae4m@jpeg',
    'associated': {'chat': {'allowIncoming': 'following'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [{'src': 'did:plc:ysxhfdhksecz64m2mon3ctxs',
      'uri': 'at://did:plc:ysxhfdhksecz64m2mon3ctxs/app.bsky.actor.profile/self',
      'cid': 'bafyreicwew233ghxa4hbjnjjxhh4347vckjganpcqg2yl5umf6mamaahka',
      'val': '!no-unauthenticated',
      'cts': '1970-01-01T00:00:00.000Z'}],
    'createdAt': '2023-07-03T16:40:46.587Z',
    'description': 'This isn’t right. This isn’t even wrong. I contain multiple ‘tudes.\n\nshe/her/hers',
    'indexedAt': '2025-03-24T19:06:49.842Z'},
   'createdAt': '2026-03-03T17:55:24.988Z',
   'indexedAt': '2026-03-03T17:55:24.988Z'},
  {'actor': {'did': 'did:plc:qmt4id5nr35gn3wuwuceexvd',
    'handle': 'littlemissteach.bsky.social',
    'displayName': 'Ali',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:qmt4id5nr35gn3wuwuceexvd/bafkreif2fhkpjywygjm4l3noavhiyrwntsmf6ouglbuv7xnlcmsfyisea4@jpeg',
    'associated': {'chat': {'allowIncoming': 'following'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-08-19T07:32:05.685Z',
    'description': 'Veteran KS1 teacher. Occasionally posts useful stuff, mostly reposts, replies and music (formerly @deputynew)\n\n🐶😊🏳️\u200d⚧️🏳️\u200d🌈 (she/her)',
    'indexedAt': '2025-08-10T21:01:52.097Z'},
   'createdAt': '2026-03-03T17:51:14.902Z',
   'indexedAt': '2026-03-03T17:51:12.962Z'},
  {'actor': {'did': 'did:plc:qx4er5wmi2yyquddvm23okom',
    'handle': 'ryvalter.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:qx4er5wmi2yyquddvm23okom/bafkreib6jzjrpoio5zpwb7ecouu5kfc6ctmmvl7cppszzforkzafk6stzu@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [{'src': 'did:plc:qx4er5wmi2yyquddvm23okom',
      'uri': 'at://did:plc:qx4er5wmi2yyquddvm23okom/app.bsky.actor.profile/self',
      'cid': 'bafyreicacjlm32zzmxurbb2bktekyjmymm4hyoti33vhz62dnpgi7tk63m',
      'val': '!no-unauthenticated',
      'cts': '2024-10-30T19:55:04.154Z'}],
    'createdAt': '2024-10-30T19:55:04.624Z',
    'indexedAt': '2024-10-30T19:56:16.128Z'},
   'createdAt': '2026-03-03T17:47:07.787Z',
   'indexedAt': '2026-03-03T17:47:07.787Z'},
  {'actor': {'did': 'did:plc:pbwvpr676ddg2deczapzyx2w',
    'handle': 'thressar.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:pbwvpr676ddg2deczapzyx2w/bafkreifdzypv2jdxi6n5keg2ki4bujxjqxakfjb2zx6hz5nls4elclsoli@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [{'src': 'did:plc:pbwvpr676ddg2deczapzyx2w',
      'uri': 'at://did:plc:pbwvpr676ddg2deczapzyx2w/app.bsky.actor.profile/self',
      'cid': 'bafyreidxtgavuzumn6qz4ujzoffqpsdguwkbs7mbsfjtucfjhcdprcmuz4',
      'val': '!no-unauthenticated',
      'cts': '2024-10-20T13:40:04.624Z'}],
    'createdAt': '2024-10-20T13:40:05.211Z',
    'indexedAt': '2024-10-22T11:47:19.707Z'},
   'createdAt': '2026-03-03T17:34:07.561Z',
   'indexedAt': '2026-03-03T17:34:07.561Z'},
  {'actor': {'did': 'did:plc:edn74kxymzw5pwombytk5qz4',
    'handle': 'lawrenceshaban.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:edn74kxymzw5pwombytk5qz4/bafkreiduask4jqc2ggmwk4543fmzxflvtuqr6mfsctnpnq7avszmp5zq4e@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2025-03-14T12:42:13.841Z',
    'indexedAt': '2025-03-14T12:42:13.841Z'},
   'createdAt': '2026-03-03T17:29:46.771Z',
   'indexedAt': '2026-03-03T17:29:46.771Z'},
  {'actor': {'did': 'did:plc:jr3kbip7e7drio4tlo7qbxrq',
    'handle': 'aecthgthean.bsky.social',
    'displayName': 'Aecth Gra Thean',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:jr3kbip7e7drio4tlo7qbxrq/bafkreid3zadcf6er6ueu6gzn5kp3winohlzkphqanflzz2frw6o673fz6u@jpeg',
    'associated': {'chat': {'allowIncoming': 'none'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-15T11:55:05.037Z',
    'description': 'A Silly Noodle from Narkoa, Csorvar\nExpect Many Wings of Fire Posts',
    'indexedAt': '2024-12-13T02:07:29.343Z'},
   'createdAt': '2026-03-03T17:28:02.097Z',
   'indexedAt': '2026-03-03T17:28:02.097Z'},
  {'actor': {'did': 'did:plc:prv74z34dbb2xsfvyowbue5v',
    'handle': 'thebirchfieldguide.bsky.social',
    'displayName': 'Jimmy',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:prv74z34dbb2xsfvyowbue5v/bafkreieuf7pq7pwoh66s7pper3zpvz3nsqs2ssmeakethd77t2pnbtbamu@jpeg',
    'associated': {'chat': {'allowIncoming': 'following'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2023-09-15T02:03:35.564Z',
    'description': 'Ecologist in Northern Ontario. I also enjoy cross country skiing, canoeing, climbing, drawing, and the occasional video game.  He/him',
    'indexedAt': '2025-10-13T00:40:21.873Z'},
   'createdAt': '2026-03-03T17:27:54.066Z',
   'indexedAt': '2026-03-03T17:27:54.066Z'},
  {'actor': {'did': 'did:plc:6h647h3agk5rgj7qb7q7rzri',
    'handle': 'allanolley.bsky.social',
    'displayName': 'Allan Olley',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:6h647h3agk5rgj7qb7q7rzri/bafkreiewcnr62e4qbaczittrony2kmf6jvm3uqzdt4echi36zmescarqke@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-08T17:33:25.584Z',
    'description': 'Fan of many things and over degreed and underemployed. Groucho Marxist. 🥸\n\nAdvocate of mining the Sun for helium. ⛏️🔆',
    'indexedAt': '2025-11-02T00:06:33.552Z'},
   'createdAt': '2026-03-03T17:17:59.096Z',
   'indexedAt': '2026-03-03T17:17:58.759Z'},
  {'actor': {'did': 'did:plc:thrfahweksv4wlvpz3s5pkpq',
    'handle': 'flight-elements.bsky.social',
    'displayName': 'Dr Andrew Skinner',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:thrfahweksv4wlvpz3s5pkpq/bafkreie443wxmwuzfaefqlryirudrca6gcy5z2kwhfx267lls6iukkvzqa@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2023-08-11T11:27:37.314Z',
    'description': 'STEEL FRAME | ORIGIN COMPLEX | BITTER EARTH\nWriting repped by @jamiecowen.bsky.social\n#PostdocLife | All opinions in beta | He/Him | Jozi boy',
    'indexedAt': '2025-10-23T14:11:44.151Z'},
   'createdAt': '2026-03-03T17:17:05.128Z',
   'indexedAt': '2026-03-03T17:17:05.128Z'},
  {'actor': {'did': 'did:plc:fsbzrpywc3pwp5feygtkcj6k',
    'handle': 'sol1496.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:fsbzrpywc3pwp5feygtkcj6k/bafkreihcnjvlsrqkzswlxpvob7qvklvid5o73ig7s2jnuzu7gurdmo4jmy@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-27T23:58:20.746Z',
    'indexedAt': '2024-11-27T23:58:20.746Z'},
   'createdAt': '2026-03-03T17:16:02.603Z',
   'indexedAt': '2026-03-03T17:16:02.453Z'},
  {'actor': {'did': 'did:plc:72h6it5mvvtrvqg7grzj2dv2',
    'handle': 'charliesierra.bsky.social',
    'displayName': 'Charlie',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:72h6it5mvvtrvqg7grzj2dv2/bafkreieagukyg34bvnhzwzfa6g2edq6gb4y47mmeyzfg2ovqtlzcdnbb2q@jpeg',
    'associated': {'chat': {'allowIncoming': 'following'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2023-10-07T19:02:18.073Z',
    'description': 'Intergalactic Space Weasel',
    'indexedAt': '2025-12-09T14:10:53.724Z'},
   'createdAt': '2026-03-03T17:13:25.337Z',
   'indexedAt': '2026-03-03T17:13:24.063Z'},
  {'actor': {'did': 'did:plc:3e7yw6tnufaadqzs62jrnrb2',
    'handle': 'scysta.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:3e7yw6tnufaadqzs62jrnrb2/bafkreifeohqtuip7ecfrfasu2jgcmwdpe3id5tmgonhv5i3ahcanj2sjji@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2025-01-23T12:09:13.043Z',
    'indexedAt': '2025-01-23T12:09:13.043Z'},
   'createdAt': '2026-03-03T17:13:02.159Z',
   'indexedAt': '2026-03-03T17:13:02.153Z'},
  {'actor': {'did': 'did:plc:u3tsuwjejeedicbqyyp5ozzj',
    'handle': 'frictorots.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:u3tsuwjejeedicbqyyp5ozzj/bafkreiefe2hy5nb3zn7mz22ozyo32q5v4ttwkhwxscgvne6yw6shgi4dwq@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [{'src': 'did:plc:u3tsuwjejeedicbqyyp5ozzj',
      'uri': 'at://did:plc:u3tsuwjejeedicbqyyp5ozzj/app.bsky.actor.profile/self',
      'cid': 'bafyreid4y5yfqobtxgtuyetmqulvmyk2237y54oiyfobv7ix63od2llysm',
      'val': '!no-unauthenticated',
      'cts': '2025-01-30T01:03:50.627Z'}],
    'createdAt': '2025-01-30T01:03:51.643Z',
    'indexedAt': '2025-02-15T20:30:42.345Z'},
   'createdAt': '2026-03-03T17:10:46.669Z',
   'indexedAt': '2026-03-03T17:10:46.567Z'},
  {'actor': {'did': 'did:plc:exrhlhf5atzay4xavck4xtxx',
    'handle': 'wwwwww.lol',
    'displayName': 'kusa',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:exrhlhf5atzay4xavck4xtxx/bafkreidsldaz4ekvjil7xvz64dkimfxj3e5etaewjxu4nvqthybhxbtiwe@jpeg',
    'associated': {'chat': {'allowIncoming': 'all'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-10-17T02:28:15.906Z',
    'description': 'some guy sometimes doing some thing @ quavergame.com\n\nrhythm game enjoyer',
    'indexedAt': '2024-10-19T05:54:22.210Z'},
   'createdAt': '2026-03-03T17:07:20.630Z',
   'indexedAt': '2026-03-03T17:07:20.630Z'},
  {'actor': {'did': 'did:plc:blkyni4chyayfwfrjuifzokj',
    'handle': 'furriest.cat',
    'displayName': 'codfish 🧶☃️',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:blkyni4chyayfwfrjuifzokj/bafkreieasfrluco5esc6uf3dr3qf3kiz6vahrqn64lsnadq2futtqpf7aa@jpeg',
    'associated': {'chat': {'allowIncoming': 'all'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2023-06-11T15:52:59.515Z',
    'description': 'meow 😸 compsci/cybersec student 🇪🇺\n23 • he/him • 🏳\u200d🌈\n🐦 https://twitter.com/codfish246\n🐘 https://tech.lgbt/@codfish246\n📍London, UK\nbanner: @riffygriff pfp: @zorrito.bsky.social \n(ask for AD)\nhttps://furry.st 🐾',
    'indexedAt': '2026-02-28T05:42:56.648Z'},
   'createdAt': '2026-03-03T17:05:54.502Z',
   'indexedAt': '2026-03-03T17:05:54.502Z'},
  {'actor': {'did': 'did:plc:ho73s3vxotamp7djyr64lnxq',
    'handle': 'dinosour.neocities.org',
    'displayName': 'Dino (Ruby)',
    'pronouns': 'they/them',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:ho73s3vxotamp7djyr64lnxq/bafkreifxsjsxlma5rkryyt6zljl77rkm3v7bh2a5js4getbbcigyslviwi@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2025-01-11T18:20:40.943Z',
    'description': "no one will read this so i will just say im nonbinary and enjoy making out with @omniscient-ai.bsky.social\n\ncheck out my website (it's the same as my handle)",
    'indexedAt': '2025-12-29T16:38:29.625Z'},
   'createdAt': '2026-03-03T17:05:37.532Z',
   'indexedAt': '2026-03-03T17:05:37.532Z'},
  {'actor': {'did': 'did:plc:b6ju7kaxrk4h6ojlaiosopyd',
    'handle': 'nickcaros.bsky.social',
    'displayName': 'NickCaros',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:b6ju7kaxrk4h6ojlaiosopyd/bafkreiegv7sce6cj2tir7azmdeqajkz2lg5h37p5s5obvsj7x2ndx5y72e@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-14T20:15:19.628Z',
    'indexedAt': '2024-11-15T00:10:13.737Z'},
   'createdAt': '2026-03-03T17:03:12.993Z',
   'indexedAt': '2026-03-03T17:03:12.993Z'},
  {'actor': {'did': 'did:plc:venxa2tqxypopcwc2eqmsbac',
    'handle': 'anonabel.bsky.social',
    'displayName': 'Democrat Haderach',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:venxa2tqxypopcwc2eqmsbac/bafkreicabwt3tisnywdzrtignkpfjddztahkoy2qnbafz5s3xurl77pbqi@jpeg',
    'associated': {'chat': {'allowIncoming': 'following'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-03-20T04:32:48.476Z',
    'description': 'I like making Dune memes. And political memes. And DuneXcrossoverXpolitical memes. \n\nNo gods, no masters.',
    'indexedAt': '2025-11-28T19:26:50.025Z'},
   'createdAt': '2026-03-03T17:01:32.613Z',
   'indexedAt': '2026-03-03T17:01:32.613Z'},
  {'actor': {'did': 'did:plc:6qndqhhy5e7skrxkqkkvpbic',
    'handle': 'wintermute201.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:6qndqhhy5e7skrxkqkkvpbic/bafkreickcdavkduymrj6xofhipqilqryvgcrqgk5rb7c72p7tmfbtepmb4@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-23T19:50:39.045Z',
    'indexedAt': '2024-11-23T19:50:39.045Z'},
   'createdAt': '2026-03-03T17:00:51.006Z',
   'indexedAt': '2026-03-03T17:00:51.006Z'},
  {'actor': {'did': 'did:plc:6hbr35ujbswqzqln7yuyig67',
    'handle': 'nuclearcodecat.bsky.social',
    'displayName': '',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:6hbr35ujbswqzqln7yuyig67/bafkreibds7q3p34g5cpx4iomt5paou5xhm2mh77psqecuago44k2klvw7a@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-10-14T15:53:07.506Z',
    'indexedAt': '2024-10-14T15:53:07.506Z'},
   'createdAt': '2026-03-03T17:00:40.768Z',
   'indexedAt': '2026-03-03T17:00:40.768Z'},
  {'actor': {'did': 'did:plc:ubkgnavhwsxtenpxj2wk3vjy',
    'handle': 'jimersonadkins.bsky.social',
    'displayName': 'Jimerson',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:ubkgnavhwsxtenpxj2wk3vjy/bafkreiadvidpb7kslj4emideyawwc5hjigy25ezzrdvy6mrdiba6ppdcty@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-11-24T10:11:53.745Z',
    'description': 'Spaceships, wizards, and wanderlust.\nLinux, FOSS, and privacy.\nTabletop, PC, and board.\nCoffee, checklists, whiskey.\nPhysics, philosophy, equity. \nBassist, writer, programmer.\nComedy, wit, and sarcasm.\nMST3K is my comfort show.',
    'indexedAt': '2026-01-22T15:03:59.924Z'},
   'createdAt': '2026-03-03T16:55:37.615Z',
   'indexedAt': '2026-03-03T16:55:37.615Z'},
  {'actor': {'did': 'did:plc:h7equgyjjewpxd6kpwnch6kc',
    'handle': 'chiciebee.bsky.social',
    'displayName': 'chiciebee',
    'associated': {'chat': {'allowIncoming': 'following'},
     'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2023-08-30T02:05:38.148Z',
    'indexedAt': '2024-01-20T06:47:40.802Z'},
   'createdAt': '2026-03-03T16:54:58.838Z',
   'indexedAt': '2026-03-03T16:54:58.251Z'},
  {'actor': {'did': 'did:plc:nl4mjx2xwjxy33uujq3f4yk7',
    'handle': 'd08aurora.bsky.social',
    'displayName': 'Aurora',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:nl4mjx2xwjxy33uujq3f4yk7/bafkreicfrrf5474bf7ll43ixlxi3cdop47evwhu3wvhinxtn7gfhvggyfe@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2024-03-13T21:52:21.971Z',
    'indexedAt': '2024-12-23T21:06:50.844Z'},
   'createdAt': '2026-03-03T16:53:50.132Z',
   'indexedAt': '2026-03-03T16:53:50.132Z'},
  {'actor': {'did': 'did:plc:mfeng2rox53gadjxmxoqkhoa',
    'handle': 'thatdarnchimera.bsky.social',
    'displayName': 'Ty',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:mfeng2rox53gadjxmxoqkhoa/bafkreialmfm66acflzyzi7phx4lvfdashprtcjuu3ml3ucvbx2zmbkk6ru@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2023-08-21T00:17:32.586Z',
    'description': 'NSFW | He/Him | 🐯💜🐺 | 🔞 | Husband of Ombre',
    'indexedAt': '2025-02-26T14:55:59.945Z'},
   'createdAt': '2026-03-03T16:48:56.881Z',
   'indexedAt': '2026-03-03T16:48:56.361Z'},
  {'actor': {'did': 'did:plc:v265sfn5on3zzvn3ud5axgin',
    'handle': 'cheshious.bsky.social',
    'displayName': 'Slightly (Gila) Monster',
    'avatar': 'https://cdn.bsky.app/img/avatar/plain/did:plc:v265sfn5on3zzvn3ud5axgin/bafkreigifeibufqgwyis5j25qexn5wfpf7z76x75742tzilmmd6erd6qle@jpeg',
    'associated': {'activitySubscription': {'allowSubscriptions': 'followers'}},
    'labels': [],
    'createdAt': '2025-01-08T17:19:02.843Z',

In [12]:
actors = []
for like in response.json()['likes']:
    actors.append(like['actor'])

likers_df = pd.DataFrame(actors)

display(likers_df.head())
print(f'found {len(likers_df)} people who liked this post')

,did,handle,displayName,avatar,associated,labels,createdAt,indexedAt,description,pronouns
0,did:plc:wb3tevjffxyws4dh6mkoitc4,pulsargig.bsky.social,,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2024-11-22T03:53:35.853Z,2024-11-22T03:53:35.853Z,NaN,NaN
1,did:plc:fc3t6zpdthu7bgbrne3g4krg,sisyphianspartacus.bsky.social,,https://cdn.bsky.app/img/avatar/plain/did:plc:...,"{'chat': {'allowIncoming': 'none'}, 'activityS...",[],2025-03-10T14:32:06.642Z,2025-05-04T22:32:03.275Z,NaN,NaN
2,did:plc:325f7xemyvavdxkkvbi67um6,1condor12.bsky.social,Steelperigren,NaN,{'activitySubscription': {'allowSubscriptions'...,[],2023-08-30T03:19:26.358Z,2024-01-20T06:38:12.379Z,He/him | 30 years old\nConsummate lurker,NaN
3,did:plc:4xn7om7w4ys7eorunku7n3w4,jjjennnnn.com,JJJENNNNN,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2024-10-27T20:30:04.109Z,2025-05-10T20:15:16.540Z,🤔 - Jʼen doute.\n\n🇨🇦 in 🇺🇸,NaN
4,did:plc:usfbknt6ptd7nqaihbhdcikc,ouromakesgames.bsky.social,Ouroboros,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2024-11-14T00:26:48.277Z,2026-01-31T23:12:12.346Z,What if we placed our Github repositories next...,NaN

found 50 people who liked this post

## Pageination

Notice how we only got 50 people as a response, while the post itself promised > 2000? That is due to a limited number of results that the BlueSky API returns by default.

We can increase this to 100 for a single request, but that is still much less than we would expect.

If we really want to capture all people who liked this post, we need to use _pageination_, i.e., do multiple requests using a _cursor_ and then combine the results.

In [13]:
url = "https://public.api.bsky.app/xrpc/app.bsky.feed.getLikes"
global_params = {
    'uri': 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mg46hoty222r',
    'limit': 100,
}
more_results = True
cursor = None
actors = []

# We continue our requests as long as there are more results
while more_results:
    # | allows us to add (multiple) new keys + values to an existing dict
    local_params = global_params | {
        'cursor': cursor
    }

    response = requests.get(url, params=local_params)
    json_response = response.json()

    # Save the actors that we found
    for like in json_response['likes']:
        actors.append(like['actor'])
    
    # A cursor is returned from the BlueSky API iff there are more results
    if 'cursor' in json_response:
        cursor = json_response['cursor']
    else:
        more_results = False
    
    # NOTE that you might want to include a small delay after each request.
    # Otherwise, you might run into rate limits and the server might reject your request.
    # We could also handle this by performing an exponential backoff when we encounter a status code 429.
    

all_likers_df = pd.DataFrame(actors)
all_likers_df

,did,handle,displayName,avatar,associated,labels,createdAt,indexedAt,description,pronouns,status,verification
0,did:plc:wb3tevjffxyws4dh6mkoitc4,pulsargig.bsky.social,,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2024-11-22T03:53:35.853Z,2024-11-22T03:53:35.853Z,NaN,NaN,NaN,NaN
1,did:plc:fc3t6zpdthu7bgbrne3g4krg,sisyphianspartacus.bsky.social,,https://cdn.bsky.app/img/avatar/plain/did:plc:...,"{'chat': {'allowIncoming': 'none'}, 'activityS...",[],2025-03-10T14:32:06.642Z,2025-05-04T22:32:03.275Z,NaN,NaN,NaN,NaN
2,did:plc:325f7xemyvavdxkkvbi67um6,1condor12.bsky.social,Steelperigren,NaN,{'activitySubscription': {'allowSubscriptions'...,[],2023-08-30T03:19:26.358Z,2024-01-20T06:38:12.379Z,He/him | 30 years old\nConsummate lurker,NaN,NaN,NaN
3,did:plc:4xn7om7w4ys7eorunku7n3w4,jjjennnnn.com,JJJENNNNN,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2024-10-27T20:30:04.109Z,2025-05-10T20:15:16.540Z,🤔 - Jʼen doute.\n\n🇨🇦 in 🇺🇸,NaN,NaN,NaN
4,did:plc:usfbknt6ptd7nqaihbhdcikc,ouromakesgames.bsky.social,Ouroboros,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2024-11-14T00:26:48.277Z,2026-01-31T23:12:12.346Z,What if we placed our Github repositories next...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2286,did:plc:o7e2hbtmvqexpbweuioy4ant,rsgreacen.bsky.social,Environmental Insurrectionist,https://cdn.bsky.app/img/avatar/plain/did:plc:...,"{'chat': {'allowIncoming': 'following'}, 'acti...",[],2024-04-19T10:52:08.698Z,2026-01-23T16:05:23.424Z,"Environmental advocate, coastal far Northern C...",NaN,NaN,NaN
2287,did:plc:56qd34vjsjb4y7f7p4fsgv6z,latinteachsmith.bsky.social,Bob Smith,https://cdn.bsky.app/img/avatar/plain/did:plc:...,"{'chat': {'allowIncoming': 'following'}, 'acti...","[{'src': 'did:plc:56qd34vjsjb4y7f7p4fsgv6z', '...",2024-04-20T11:46:51.442Z,2025-11-01T14:36:05.451Z,"citizen of planet Earth, Star Wars fan, board ...",NaN,NaN,NaN
2288,did:plc:g6zf2sowg6z7h6kbsrzwtzuf,arcticfoxnetwork.bsky.social,No Name (It/We)🏳️‍⚧️,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2025-12-27T10:12:20.424Z,2026-01-29T17:04:21.546Z,NaN,NaN,NaN,NaN
2289,did:plc:tvzetckkl7vpvzm7sdsg6xop,phroodloops.bsky.social,Pink Freud,https://cdn.bsky.app/img/avatar/plain/did:plc:...,{'activitySubscription': {'allowSubscriptions'...,[],2024-12-04T19:04:56.445Z,2025-11-25T01:18:03.224Z,"""Insomnio tiene el que no está durmiendo con e...",NaN,NaN,NaN
2290,did:plc:vzp4tndhcwnhtbuizv7wupvc,blueishmage.bsky.social,BlueishMage,https://cdn.bsky.app/img/avatar/plain/did:plc:...,"{'chat': {'allowIncoming': 'following'}, 'acti...",[],2023-09-08T06:49:48.600Z,2024-11-01T12:10:12.079Z,Dutchman on an anglo-centric internet.\n\nRece...,NaN,NaN,NaN

## ATProto Python Client

For ATProto, the protocol behind the BlueSky API, there is actually a python wrapper that lets us gather this kind of data a bit more conveniently.

It allows us to use Python objects directly and it also handles rate limits.

In [ ]:
from atproto import Client

In [15]:
client = Client(base_url='https://public.api.bsky.app') # use the public API without authentification
client

In [16]:
response = client.get_likes('at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mg46hoty222r')
response.likes

[Like(actor=ProfileView(did='did:plc:wb3tevjffxyws4dh6mkoitc4', handle='pulsargig.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:wb3tevjffxyws4dh6mkoitc4/bafkreigt342zzmmaq3hs4uuhrjlhd5n3fzrdniltklryya5p24ea2xwkge@jpeg', created_at='2024-11-22T03:53:35.853Z', debug=None, description=None, display_name='', indexed_at='2024-11-22T03:53:35.853Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T18:05:51.153Z', indexed_at='2026-03-03T18:05:51.153Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:fc3t6zpdthu7bgbrne3g4krg', handle='sisyphianspartacus.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='none', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:fc3t6zpdthu7bgbrne3g4krg/bafkreic2u2tibbixdwuzlqxhtmijhec2kzh3jws32mm3zxsuitujredcme@jpeg', created_at='2025-03-10T14:32:06.642Z', debug=None, description=None, display_name='', indexed_at='2025-05-04T22:32:03.275Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T18:04:47.877Z', indexed_at='2026-03-03T18:04:47.877Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:325f7xemyvavdxkkvbi67um6', handle='1condor12.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar=None, created_at='2023-08-30T03:19:26.358Z', debug=None, description='He/him | 30 years old\nConsummate lurker', display_name='Steelperigren', indexed_at='2024-01-20T06:38:12.379Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T18:01:49.868Z', indexed_at='2026-03-03T18:01:49.259Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:4xn7om7w4ys7eorunku7n3w4', handle='jjjennnnn.com', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:4xn7om7w4ys7eorunku7n3w4/bafkreibzyt2jsibz7u7xs3kg7oidsl5mptk2y3kg2l5hoizfccj5wbhwoq@jpeg', created_at='2024-10-27T20:30:04.109Z', debug=None, description='🤔 - Jʼen doute.\n\n🇨🇦 in 🇺🇸', display_name='JJJENNNNN', indexed_at='2025-05-10T20:15:16.540Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T18:00:26.061Z', indexed_at='2026-03-03T18:00:26.061Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:usfbknt6ptd7nqaihbhdcikc', handle='ouromakesgames.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:usfbknt6ptd7nqaihbhdcikc/bafkreicwcx7cluradw7ryqjowgsd6n2vhk7nztsmp7p4qqoe3w22o2gkg4@jpeg', created_at='2024-11-14T00:26:48.277Z', debug=None, description='What if we placed our Github repositories next to each other...?\n🇨🇦', display_name='Ouroboros', indexed_at='2026-01-31T23:12:12.346Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:55:37.882Z', indexed_at='2026-03-03T17:55:37.882Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:ysxhfdhksecz64m2mon3ctxs', handle='krikalitika.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='following', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:ysxhfdhksecz64m2mon3ctxs/bafkreieko6arzmyhipbmf2lwbpdss3bdtszkqqwsjljgqshkeklcteae4m@jpeg', created_at='2023-07-03T16:40:46.587Z', debug=None, description='This isn’t right. This isn’t even wrong. I contain multiple ‘tudes.\n\nshe/her/hers', display_name='Turing Pest', indexed_at='2025-03-24T19:06:49.842Z', labels=[Label(cts='1970-01-01T00:00:00.000Z', src='did:plc:ysxhfdhksecz64m2mon3ctxs', uri='at://did:plc:ysxhfdhksecz64m2mon3ctxs/app.bsky.actor.profile/self', val='!no-unauthenticated', cid='bafyreicwew233ghxa4hbjnjjxhh4347vckjganpcqg2yl5umf6mamaahka', exp=None, neg=None, sig=None, ver=None, py_type='com.atproto.label.defs#label')], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:55:24.988Z', indexed_at='2026-03-03T17:55:24.988Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:qmt4id5nr35gn3wuwuceexvd', handle='littlemissteach.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='following', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:qmt4id5nr35gn3wuwuceexvd/bafkreif2fhkpjywygjm4l3noavhiyrwntsmf6ouglbuv7xnlcmsfyisea4@jpeg', created_at='2024-08-19T07:32:05.685Z', debug=None, description='Veteran KS1 teacher. Occasionally posts useful stuff, mostly reposts, replies and music (formerly @deputynew)\n\n🐶😊🏳️\u200d⚧️🏳️\u200d🌈 (she/her)', display_name='Ali', indexed_at='2025-08-10T21:01:52.097Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:51:14.902Z', indexed_at='2026-03-03T17:51:12.962Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:qx4er5wmi2yyquddvm23okom', handle='ryvalter.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:qx4er5wmi2yyquddvm23okom/bafkreib6jzjrpoio5zpwb7ecouu5kfc6ctmmvl7cppszzforkzafk6stzu@jpeg', created_at='2024-10-30T19:55:04.624Z', debug=None, description=None, display_name='', indexed_at='2024-10-30T19:56:16.128Z', labels=[Label(cts='2024-10-30T19:55:04.154Z', src='did:plc:qx4er5wmi2yyquddvm23okom', uri='at://did:plc:qx4er5wmi2yyquddvm23okom/app.bsky.actor.profile/self', val='!no-unauthenticated', cid='bafyreicacjlm32zzmxurbb2bktekyjmymm4hyoti33vhz62dnpgi7tk63m', exp=None, neg=None, sig=None, ver=None, py_type='com.atproto.label.defs#label')], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:47:07.787Z', indexed_at='2026-03-03T17:47:07.787Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:pbwvpr676ddg2deczapzyx2w', handle='thressar.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:pbwvpr676ddg2deczapzyx2w/bafkreifdzypv2jdxi6n5keg2ki4bujxjqxakfjb2zx6hz5nls4elclsoli@jpeg', created_at='2024-10-20T13:40:05.211Z', debug=None, description=None, display_name='', indexed_at='2024-10-22T11:47:19.707Z', labels=[Label(cts='2024-10-20T13:40:04.624Z', src='did:plc:pbwvpr676ddg2deczapzyx2w', uri='at://did:plc:pbwvpr676ddg2deczapzyx2w/app.bsky.actor.profile/self', val='!no-unauthenticated', cid='bafyreidxtgavuzumn6qz4ujzoffqpsdguwkbs7mbsfjtucfjhcdprcmuz4', exp=None, neg=None, sig=None, ver=None, py_type='com.atproto.label.defs#label')], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:34:07.561Z', indexed_at='2026-03-03T17:34:07.561Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:edn74kxymzw5pwombytk5qz4', handle='lawrenceshaban.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:edn74kxymzw5pwombytk5qz4/bafkreiduask4jqc2ggmwk4543fmzxflvtuqr6mfsctnpnq7avszmp5zq4e@jpeg', created_at='2025-03-14T12:42:13.841Z', debug=None, description=None, display_name='', indexed_at='2025-03-14T12:42:13.841Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:29:46.771Z', indexed_at='2026-03-03T17:29:46.771Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:jr3kbip7e7drio4tlo7qbxrq', handle='aecthgthean.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='none', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:jr3kbip7e7drio4tlo7qbxrq/bafkreid3zadcf6er6ueu6gzn5kp3winohlzkphqanflzz2frw6o673fz6u@jpeg', created_at='2024-11-15T11:55:05.037Z', debug=None, description='A Silly Noodle from Narkoa, Csorvar\nExpect Many Wings of Fire Posts', display_name='Aecth Gra Thean', indexed_at='2024-12-13T02:07:29.343Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:28:02.097Z', indexed_at='2026-03-03T17:28:02.097Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:prv74z34dbb2xsfvyowbue5v', handle='thebirchfieldguide.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='following', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:prv74z34dbb2xsfvyowbue5v/bafkreieuf7pq7pwoh66s7pper3zpvz3nsqs2ssmeakethd77t2pnbtbamu@jpeg', created_at='2023-09-15T02:03:35.564Z', debug=None, description='Ecologist in Northern Ontario. I also enjoy cross country skiing, canoeing, climbing, drawing, and the occasional video game.  He/him', display_name='Jimmy', indexed_at='2025-10-13T00:40:21.873Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:27:54.066Z', indexed_at='2026-03-03T17:27:54.066Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:6h647h3agk5rgj7qb7q7rzri', handle='allanolley.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:6h647h3agk5rgj7qb7q7rzri/bafkreiewcnr62e4qbaczittrony2kmf6jvm3uqzdt4echi36zmescarqke@jpeg', created_at='2024-11-08T17:33:25.584Z', debug=None, description='Fan of many things and over degreed and underemployed. Groucho Marxist. 🥸\n\nAdvocate of mining the Sun for helium. ⛏️🔆', display_name='Allan Olley', indexed_at='2025-11-02T00:06:33.552Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:17:59.096Z', indexed_at='2026-03-03T17:17:58.759Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:thrfahweksv4wlvpz3s5pkpq', handle='flight-elements.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:thrfahweksv4wlvpz3s5pkpq/bafkreie443wxmwuzfaefqlryirudrca6gcy5z2kwhfx267lls6iukkvzqa@jpeg', created_at='2023-08-11T11:27:37.314Z', debug=None, description='STEEL FRAME | ORIGIN COMPLEX | BITTER EARTH\nWriting repped by @jamiecowen.bsky.social\n#PostdocLife | All opinions in beta | He/Him | Jozi boy', display_name='Dr Andrew Skinner', indexed_at='2025-10-23T14:11:44.151Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:17:05.128Z', indexed_at='2026-03-03T17:17:05.128Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:fsbzrpywc3pwp5feygtkcj6k', handle='sol1496.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:fsbzrpywc3pwp5feygtkcj6k/bafkreihcnjvlsrqkzswlxpvob7qvklvid5o73ig7s2jnuzu7gurdmo4jmy@jpeg', created_at='2024-11-27T23:58:20.746Z', debug=None, description=None, display_name='', indexed_at='2024-11-27T23:58:20.746Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:16:02.603Z', indexed_at='2026-03-03T17:16:02.453Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:72h6it5mvvtrvqg7grzj2dv2', handle='charliesierra.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='following', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:72h6it5mvvtrvqg7grzj2dv2/bafkreieagukyg34bvnhzwzfa6g2edq6gb4y47mmeyzfg2ovqtlzcdnbb2q@jpeg', created_at='2023-10-07T19:02:18.073Z', debug=None, description='Intergalactic Space Weasel', display_name='Charlie', indexed_at='2025-12-09T14:10:53.724Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:13:25.337Z', indexed_at='2026-03-03T17:13:24.063Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:3e7yw6tnufaadqzs62jrnrb2', handle='scysta.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:3e7yw6tnufaadqzs62jrnrb2/bafkreifeohqtuip7ecfrfasu2jgcmwdpe3id5tmgonhv5i3ahcanj2sjji@jpeg', created_at='2025-01-23T12:09:13.043Z', debug=None, description=None, display_name='', indexed_at='2025-01-23T12:09:13.043Z', labels=[], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:13:02.159Z', indexed_at='2026-03-03T17:13:02.153Z', py_type='app.bsky.feed.getLikes#like'),
 Like(actor=ProfileView(did='did:plc:u3tsuwjejeedicbqyyp5ozzj', handle='frictorots.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:u3tsuwjejeedicbqyyp5ozzj/bafkreiefe2hy5nb3zn7mz22ozyo32q5v4ttwkhwxscgvne6yw6shgi4dwq@jpeg', created_at='2025-01-30T01:03:51.643Z', debug=None, description=None, display_name='', indexed_at='2025-02-15T20:30:42.345Z', labels=[Label(cts='2025-01-30T01:03:50.627Z', src='did:plc:u3tsuwjejeedicbqyyp5ozzj', uri='at://did:plc:u3tsuwjejeedicbqyyp5ozzj/app.bsky.actor.profile/self', val='!no-unauthenticated', cid='bafyreid4y5yfqobtxgtuyetmqulvmyk2237y54oiyfobv7ix63od2llysm', exp=None, neg=None, sig=None, ver=None, py_type='com.atproto.label.defs#label')], pronouns=None, status=None, verification=None, viewer=None, py_type='app.bsky.actor.defs#profileView'), created_at='2026-03-03T17:10:46.669Z', indexed_at='2026-03-03T17:10:46.567Z', py_type='app.bsky.feed.getLikes#like'),

In [17]:
pd.DataFrame([dict(liker['actor']) for liker in response.likes]).head()

,did,handle,associated,avatar,created_at,debug,description,display_name,indexed_at,labels,pronouns,status,verification,viewer,py_type
0,did:plc:wb3tevjffxyws4dh6mkoitc4,pulsargig.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-11-22T03:53:35.853Z,None,NaN,,2024-11-22T03:53:35.853Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
1,did:plc:fc3t6zpdthu7bgbrne3g4krg,sisyphianspartacus.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2025-03-10T14:32:06.642Z,None,NaN,,2025-05-04T22:32:03.275Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
2,did:plc:325f7xemyvavdxkkvbi67um6,1condor12.bsky.social,activity_subscription=ProfileAssociatedActivit...,NaN,2023-08-30T03:19:26.358Z,None,He/him | 30 years old\nConsummate lurker,Steelperigren,2024-01-20T06:38:12.379Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
3,did:plc:4xn7om7w4ys7eorunku7n3w4,jjjennnnn.com,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-10-27T20:30:04.109Z,None,🤔 - Jʼen doute.\n\n🇨🇦 in 🇺🇸,JJJENNNNN,2025-05-10T20:15:16.540Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
4,did:plc:usfbknt6ptd7nqaihbhdcikc,ouromakesgames.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-11-14T00:26:48.277Z,None,What if we placed our Github repositories next...,Ouroboros,2026-01-31T23:12:12.346Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView

Again, let's add pageination:

In [18]:
post_uri = 'at://did:plc:cz73r7iyiqn26upot4jtjdhk/app.bsky.feed.post/3mg46hoty222r'

more_results = True
cursor = None
actors = []

# We continue our requests as long as there are more results
while more_results:
    response = client.get_likes(post_uri, cursor=cursor, limit=100)
    actors += [dict(liker['actor']) for liker in response.likes]

    # A cursor is returned from the BlueSky API iff there are more results
    if response.cursor is not None:
        cursor = response.cursor
    else:
        more_results = False

likers_df2 = pd.DataFrame(actors)
likers_df2

,did,handle,associated,avatar,created_at,debug,description,display_name,indexed_at,labels,pronouns,status,verification,viewer,py_type
0,did:plc:wb3tevjffxyws4dh6mkoitc4,pulsargig.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-11-22T03:53:35.853Z,None,NaN,,2024-11-22T03:53:35.853Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
1,did:plc:fc3t6zpdthu7bgbrne3g4krg,sisyphianspartacus.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2025-03-10T14:32:06.642Z,None,NaN,,2025-05-04T22:32:03.275Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
2,did:plc:325f7xemyvavdxkkvbi67um6,1condor12.bsky.social,activity_subscription=ProfileAssociatedActivit...,NaN,2023-08-30T03:19:26.358Z,None,He/him | 30 years old\nConsummate lurker,Steelperigren,2024-01-20T06:38:12.379Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
3,did:plc:4xn7om7w4ys7eorunku7n3w4,jjjennnnn.com,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-10-27T20:30:04.109Z,None,🤔 - Jʼen doute.\n\n🇨🇦 in 🇺🇸,JJJENNNNN,2025-05-10T20:15:16.540Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
4,did:plc:usfbknt6ptd7nqaihbhdcikc,ouromakesgames.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-11-14T00:26:48.277Z,None,What if we placed our Github repositories next...,Ouroboros,2026-01-31T23:12:12.346Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286,did:plc:o7e2hbtmvqexpbweuioy4ant,rsgreacen.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-04-19T10:52:08.698Z,None,"Environmental advocate, coastal far Northern C...",Environmental Insurrectionist,2026-01-23T16:05:23.424Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
2287,did:plc:56qd34vjsjb4y7f7p4fsgv6z,latinteachsmith.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-04-20T11:46:51.442Z,None,"citizen of planet Earth, Star Wars fan, board ...",Bob Smith,2025-11-01T14:36:05.451Z,[cts='2024-04-20T11:46:53.048Z' src='did:plc:5...,NaN,None,None,None,app.bsky.actor.defs#profileView
2288,did:plc:g6zf2sowg6z7h6kbsrzwtzuf,arcticfoxnetwork.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2025-12-27T10:12:20.424Z,None,NaN,No Name (It/We)🏳️‍⚧️,2026-01-29T17:04:21.546Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
2289,did:plc:tvzetckkl7vpvzm7sdsg6xop,phroodloops.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2024-12-04T19:04:56.445Z,None,"""Insomnio tiene el que no está durmiendo con e...",Pink Freud,2025-11-25T01:18:03.224Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView
2290,did:plc:vzp4tndhcwnhtbuizv7wupvc,blueishmage.bsky.social,activity_subscription=ProfileAssociatedActivit...,https://cdn.bsky.app/img/avatar/plain/did:plc:...,2023-09-08T06:49:48.600Z,None,Dutchman on an anglo-centric internet.\n\nRece...,BlueishMage,2024-11-01T12:10:12.079Z,[],NaN,None,None,None,app.bsky.actor.defs#profileView

## Authentification

The _public_ BlueSky API already allows you to do a lot of things without needing to login.
However, for specific actions, a login is required.

You can set up an app password that can be revoked easier and does not give your Python script access to your private messages: https://bsky.app/settings/privacy-and-security

While BlueSky already allows you to do many things with the public API, other services might not have a public API or might impose much stricter rate limits without login.
For instance, when using LLMs through the APIs of some of the common providers (OpenAI, Google, Anthropic, etc.), you have to login so that your LLM usage can be tracked and billed accordingly.
Make sure to check the documentation for each API that you might want to use.

In [ ]:
pwd_client = Client()
pwd_client.login(
    login = 'wanlo.bsky.social',
    password = '' # TODO: add you own app password
)

In [50]:
feed = pwd_client.get_author_feed('netzpolitik.org')
latest_post = feed.feed[0].post
latest_post

PostView(author=ProfileViewBasic(did='did:plc:bd2ad25frux6jav66chr6aiw', handle='netzpolitik.org', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='following', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:bd2ad25frux6jav66chr6aiw/bafkreiad2h326vig3y2ruamzyt447eh2wwnwgda7k33himl4utdeftzgqy@jpeg', created_at='2023-09-27T13:49:36.871Z', debug=None, display_name='netzpolitik.org', labels=[], pronouns=None, status=None, verification=VerificationState(trusted_verifier_status='none', verifications=[VerificationView(created_at='2025-07-24T01:40:45.708Z', is_valid=True, issuer='did:plc:z72i7hdynmk6r22z27h6tvur', uri='at://did:plc:z72i7hdynmk6r22z27h6tvur/app.bsky.graph.verification/3luofp2pupu24', py_type='app.bsky.actor.defs#verificationView')], verified_status='valid', py_type='app.bsky.actor.defs#verificationState'), viewer=ViewerState(activity_subscription=None, blocked_by=False, blocking=None, blocking_by_list=None, followed_by=None, following='at://did:plc:vlye5thb57ftgmh3ofe64rvq/app.bsky.graph.follow/3kfbhx4fww42a', known_followers=None, muted=False, muted_by_list=None, py_type='app.bsky.actor.defs#viewerState'), py_type='app.bsky.actor.defs#profileViewBasic'), cid='bafyreickaozkh4dqkrkitu6gjttmozco32mp5xz3ih4tl5f5iib3yvkwy4', indexed_at='2026-03-04T06:49:57.594Z', record=Record(created_at='2026-03-04T06:49:52.690Z', text='Berlins Feuerwehrleute fürchten, dass Bodycams bei Rettungseinsätzen das Vertrauensverhältnis zu den Patient*innen zerstören. Dennoch müssen sie welche tragen. Jetzt kam heraus: Die Aufnahmen sind nutzlos.\n\nnetzpolitik.org/2026/berlin-...', embed=Main(external=External(description='Berlins Feuerwehrleute fürchten, dass Bodycams bei Rettungseinsätzen das Vertrauensverhältnis zu den Patient*innen zerstören. Dennoch müssen sie welche tragen. Jetzt kam heraus: Die Aufnahmen sind nut...', title='Berlin: Bodycams an Rettungskräften sind überflüssig', uri='https://netzpolitik.org/2026/berlin-bodycams-an-rettungskraeften-sind-ueberfluessig/', thumb=BlobRef(mime_type='image/jpeg', size=841534, ref=IpldLink(link='bafkreiavclrmf3yn3bvuqg76doltanmsfip4j7el3iebr2aktcp6dni2wu'), py_type='blob'), py_type='app.bsky.embed.external#external'), py_type='app.bsky.embed.external'), entities=None, facets=[Main(features=[Link(uri='https://netzpolitik.org/2026/berlin-bodycams-an-rettungskraeften-sind-ueberfluessig/', py_type='app.bsky.richtext.facet#link')], index=ByteSlice(byte_end=243, byte_start=212, py_type='app.bsky.richtext.facet#byteSlice'), py_type='app.bsky.richtext.facet')], labels=None, langs=['de'], reply=None, tags=None, py_type='app.bsky.feed.post'), uri='at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky.feed.post/3mg7ox42dvc26', bookmark_count=4, debug=None, embed=View(external=ViewExternal(description='Berlins Feuerwehrleute fürchten, dass Bodycams bei Rettungseinsätzen das Vertrauensverhältnis zu den Patient*innen zerstören. Dennoch müssen sie welche tragen. Jetzt kam heraus: Die Aufnahmen sind nut...', title='Berlin: Bodycams an Rettungskräften sind überflüssig', uri='https://netzpolitik.org/2026/berlin-bodycams-an-rettungskraeften-sind-ueberfluessig/', thumb='https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:bd2ad25frux6jav66chr6aiw/bafkreiavclrmf3yn3bvuqg76doltanmsfip4j7el3iebr2aktcp6dni2wu@jpeg', py_type='app.bsky.embed.external#viewExternal'), py_type='app.bsky.embed.external#view'), labels=[], like_count=62, quote_count=1, reply_count=2, repost_count=22, threadgate=None, viewer=ViewerState(bookmarked=True, embedding_disabled=False, like=None, pinned=None, reply_disabled=None, repost=None, thread_muted=False, py_type='app.bsky.feed.defs#viewerState'), py_type='app.bsky.feed.defs#postView')

In [51]:
pwd_client.app.bsky.bookmark.create_bookmark(
    {
        "uri": latest_post.uri,
        # CIDs go beyond URIs and allow you to reference a specific version of a post
        "cid": latest_post.cid,
    }
)

True

## Task: Identify BlueSky accounts that have recently reposted @netzpolitik.org

Based on the display names and self-descriptions of these accounts, would you say that there are many bots?

In [ ]:
# Import tqdm for a progress bar
from tqdm.auto import tqdm

In [ ]:
# Retrieve the first 50 posts
feed = client.get_author_feed('netzpolitik.org')

In [ ]:
actors = []

# Iterate over the first 50 posts that we retrieved
for feed_post in tqdm(feed.feed):
    # skip reposts by netzpolitik.org
    if feed_post.post.author.handle != 'netzpolitik.org':
        continue

    more_results = True
    cursor = None

    # We continue our requests as long as there are more results
    while more_results:
        # Get all actors that reposted this post
        response = client.get_reposted_by(feed_post.post.uri, cursor=cursor, limit=100)
        for reposter in response.reposted_by:
            actors.append({
                'handle': reposter.handle,
                'display_name': reposter.display_name,
                'description': reposter.description,
                'post_uri': feed_post.post.uri,
            })

        # A cursor is returned from the BlueSky API iff there are more results
        if response.cursor is not None:
            cursor = response.cursor
        else:
            more_results = False

reposters_df = pd.DataFrame(actors)
reposters_df

100%|██████████| 50/50 [00:08<00:00,  5.84it/s]

,display_name,description,post_uri
0,Clarence,NaN,at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
1,Dagmar Hoffmann,Prof of Media and Communication | Gender Media...,at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
2,No Idea But Science,"Science, SciFi, IT, F(L)OSS, Covid (not over) ...",at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
3,Erdmeister,Am Abend fühle ich mich dem Morgen gewachsen.\n,at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
4,Eudoxus,#FCKNZS #FCKAFD #AfDVerbot 333ppm,at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
...,...,...,...
1723,,NaN,at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
1724,Roger Raeder°,| Musikfreak | Lehrer FöL PoWi | Christ | Drum...,at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
1725,Mutter des Chaos,Mutter des großen (K1) und des kleinen Chaos (K2),at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
1726,Simon,"Radsport, Menschenrechte, Arbeitnehmer*Innenre...",at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...
1727,blaubeere86.bsky.social,Neuer Account von vorher blaubeerblue86\n\nLiv...,at://did:plc:bd2ad25frux6jav66chr6aiw/app.bsky...