# Tutorial 05: Wikipedia API and data cleaning

Author: Maximilian Kreutner

In this notebook we will find all members of the current european parliament using wikidata.

Then, we will use the [python wrapper around the Wikipedia-API](https://github.com/martin-majlis/Wikipedia-API) to download their full biographies, clean the text, and extract their social media usernames.

In [ ]:
# Install dependencies
!pip install Wikipedia-API pandas requests tqdm beautifulsoup4

In [ ]:
# import dependencies
import time

import pandas as pd

import requests
import wikipediaapi

import re

from tqdm import tqdm

from urllib.parse import unquote, urljoin, urlparse

from bs4 import BeautifulSoup

## Using Wikidata to get a Clean List of Politicians

[Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page) is the structured database behind Wikipedia. Instead of parsing a messy Wikipedia table, we can write a SPARQL query to ask Wikidata directly for: 

*"Give me all people whose position held is Member of the European Parliament for the 10th term, and give me their English Wikipedia article URL and optionally if they have their own website, their website url."*


If you want to try out more queries and examples, you can check the [official query page](https://query.wikidata.org/#).

In [22]:
# Define our User-Agent (Required by Wikimedia Foundation)
USER_AGENT = "DataCleaningClass (maximilian.kreutner@uni-mannheim.de)"

# SPARQL query to get current MEPs (10th term = Q114425478)
sparql_query = """
SELECT ?person ?personLabel ?article ?officialWebsite WHERE {
  ?person p:P39 ?statement .
  ?statement ps:P39 wd:Q27169 ;              # Member of the European Parliament
             pq:P2937 wd:Q114425478 .        # Tenth European Parliament

  OPTIONAL { ?person wdt:P856 ?officialWebsite . }   # official website
  ?article schema:about ?person ;
           schema:isPartOf <https://en.wikipedia.org/> .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } # We only want the english articles
}
ORDER BY ?person
"""

title = "https://query.wikidata.org/sparql"
headers = {
    "User-Agent": USER_AGENT,
    "Accept": "application/sparql-results+json"
}

response = requests.get(
    title,
    headers=headers,
    params={"query": sparql_query, "format": "json"},
    timeout=60
)

response.raise_for_status()
data = response.json()
data

{'head': {'vars': ['person', 'personLabel', 'article', 'officialWebsite']},
 'results': {'bindings': [{'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q102395874'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Zsuzsanna_Borvend%C3%A9g'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Zsuzsanna Borvendég'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q10303913'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Isilda_Gomes'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Isilda Gomes'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q104070010'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Claudiu_T%C3%A2rziu'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Claudiu Târziu'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q104126196'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Emma_Wiesner'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Emma Wiesner'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q104381399'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Diana_%C8%98o%C8%99oac%C4%83'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Diana Șoșoacă'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q104598998'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Adrian-George_Axinia'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Adrian Axinia'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q105080282'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Friedrich_P%C3%BCrner'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Friedrich Pürner'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1055321'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Lucia_Annunziata'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Lucia Annunziata'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1055587'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Mario_Mantovani'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Mario Mantovani'},
    'officialWebsite': {'type': 'uri',
     'value': 'http://www.mariomantovani.it'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q105964502'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Joachim_Streit'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Joachim Streit'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q106133800'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Sebastiaan_St%C3%B6teler'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Sebastiaan Stöteler'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q106518433'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Thijs_Reuten'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Thijs Reuten'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q106518433'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Thijs_Reuten'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Thijs Reuten'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q107316188'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Aleksandar_Nikolic_(politician)'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Aleksandar Nikolic'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q107355967'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Michalis_Hatzipantelas'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Michalis Catzipantela'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1077655'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Aldo_Patriciello'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Aldo Patriciello'},
    'officialWebsite': {'type': 'uri', 'value': 'http://www.patriciello.it'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q108308348'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Emma_Rafowicz'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Emma Rafowicz'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1083771'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Christine_Schneider'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Christine Schneider'},
    'officialWebsite': {'type': 'uri',
     'value': 'https://www.christine-schneider.de/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q108731355'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Ond%C5%99ej_Dost%C3%A1l'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Ondřej Dostál'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q108736'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Birgit_Sippel'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Birgit Sippel'},
    'officialWebsite': {'type': 'uri', 'value': 'http://www.birgitsippel.de'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q108788753'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Rudi_Kennes'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Rudi Kennes'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q109468729'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Lena_Schilling'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Lena Schilling'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q109918947'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Nikola_Minchev'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Nikola Minchev'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q109968699'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Annam%C3%A1ria_Vicsek'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Annamária Vicsek'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q110213949'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Pierre-Romain_Thionnet'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Pierre-Romain Thionnet'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q110513292'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Camilla_Laureti'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Camilla Laureti'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q110635584'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Sofie_Eriksson'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Sofie Eriksson'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11074254'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Biljana_Borzan'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Biljana Borzan'},
    'officialWebsite': {'type': 'uri',
     'value': 'http://www.biljanaborzan.eu/hr/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q110794778'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Ren%C3%A9_Repasi'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'René Repasi'},
    'officialWebsite': {'type': 'uri', 'value': 'https://repasi.eu/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q110970031'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Anna_St%C3%BCrgkh'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Anna Stürgkh'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1112658'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Maria_Noichl'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Maria Noichl'},
    'officialWebsite': {'type': 'uri', 'value': 'http://maria-noichl.eu/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q111353622'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Rosa_Mar%C3%ADa_Serrano_Sierra'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Rosa María Serrano Sierra'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q111435'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Jan-Christoph_Oetjen'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Jan-Christoph Oetjen'},
    'officialWebsite': {'type': 'uri',
     'value': 'https://janchristoph-oetjen.europa.fdp.de/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q111796425'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Rody_Tolassy'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Rody Tolassy'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q112472001'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/%C4%BDubica_Karva%C5%A1ov%C3%A1'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Ľubica Karvašová'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q112650871'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Anne-Sophie_Frigout'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Anne-Sophie Frigout'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q112652864'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Marina_Mesure'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Marina Mesure'},
    'officialWebsite': {'type': 'uri', 'value': 'https://marinamesure.fr'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q113016342'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Jana_Nagyov%C3%A1_(politician)'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Jana Nagyová'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q113453333'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Stephen_Nikola_Bartulica'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Stephen Nikola Bartulica'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q114031217'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Beatrice_Timgren'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Beatrice Rugland Timgren'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q114363384'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Matthias_Ecke'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Matthias Ecke'},
    'officialWebsite': {'type': 'uri', 'value': 'https://matthias-ecke.eu/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q114398640'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Sebasti%C3%A3o_Bugalho'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Sebastião Bugalho'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q115056535'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Denis_Nesci'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Denis Nesci'},
    'officialWebsite': {'type': 'uri', 'value': 'https://www.denisnesci.it/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q115139975'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Stanislav_Stoyanov_(politician)'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Stanislav Stoyanov'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1157638'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Dainius_%C5%BDalimas'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Dainius Žalimas'},
    'officialWebsite': {'type': 'uri', 'value': 'https://dainiuszalimas.lt/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11688652'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Borys_Budka'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Borys Budka'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q117037367'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Roberto_Vannacci'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Roberto Vannacci'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11715524'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Jacek_Protas'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Jacek Protas'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q117409487'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/S%C3%A9rgio_Humberto'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Sérgio Humberto'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11749266'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Krzysztof_Hetman'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Krzysztof Hetman'},
    'officialWebsite': {'type': 'uri',
     'value': 'http://krzysztofhetman.pl/en/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11767619'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Marcin_Kierwi%C5%84ski'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Marcin Kierwiński'},
    'officialWebsite': {'type': 'uri', 'value': 'https://kierwinski2024.pl'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11778705'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Micha%C5%82_Dworczyk'},
    'personLabel': {'type': 'literal', 'value': 'Q11778705'},
    'officialWebsite': {'type': 'uri', 'value': 'https://dworczyk.pl'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11778888'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Micha%C5%82_Kobosko'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Michał Kobosko'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11813593'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Patryk_Jaki'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Patryk Jaki'},
    'officialWebsite': {'type': 'uri', 'value': 'http://jaki.pl'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11857612'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Elsi_Katainen'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Elsi Katainen'},
    'officialWebsite': {'type': 'uri', 'value': 'http://www.elsikatainen.fi'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q118669796'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Fredis_Beleris'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Fredis Beleris'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11880159'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Veronika_Vrecionov%C3%A1'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Veronika Vrecionová'},
    'officialWebsite': {'type': 'uri', 'value': 'https://vrecionova.cz'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q11917597'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Dolors_Montserrat'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Dolors Montserrat i Montserrat'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q119397784'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Alexandra_Mehnert'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Alexandra Mehnert'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q120015161'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Andrea_Wechsler'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Andrea Wechsler'},
    'officialWebsite': {'type': 'uri',
     'value': 'https://andrea-wechsler.de/'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q12022507'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Jan_Farsk%C3%BD'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Jan Farský'},
    'officialWebsite': {'type': 'uri', 'value': 'https://www.janfarsky.cz'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q12028942'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Kate%C5%99ina_Kone%C4%8Dn%C3%A1'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Kateřina Konečná'},
    'officialWebsite': {'type': 'uri', 'value': 'https://www.konecna.cz'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q12059351'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Tom%C3%A1%C5%A1_Zdechovsk%C3%BD'},
    'personLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Tomáš Zdechovský'},
    'officialWebsite': {'type': 'uri', 'value': 'http://zdechovsky.eu'}},
   {'person': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q120912782'},
    'article': {'type': 'uri',
     'value': 'https://en.wikipedia.org/wiki/Nikolas_Farantouris'},

We get back a json. Fill that data into a DataFrame which contains the columns: `name`, `official_website`, `wiki_title` and `URL`.
The wiki title is the last part of the URL after the last `/`.

In [23]:
mep_list = []
for item in data['results']['bindings']:
    name = item['personLabel']['value']
    # Extract the exact title from the URL and decode URL characters
    raw_url = item['article']['value']

    # Make sure to keep no official website in mind
    official_website = item.get("officialWebsite", {}).get("value")

    title = unquote(raw_url.split('/')[-1]) 
    mep_list.append({'name': name, "official_website":official_website , 'wiki_title': title, "URL": raw_url})

df = pd.DataFrame(mep_list)
display(df)

,name,official_website,wiki_title,URL
0,Zsuzsanna Borvendég,NaN,Zsuzsanna_Borvendég,https://en.wikipedia.org/wiki/Zsuzsanna_Borven...
1,Isilda Gomes,NaN,Isilda_Gomes,https://en.wikipedia.org/wiki/Isilda_Gomes
2,Claudiu Târziu,NaN,Claudiu_Târziu,https://en.wikipedia.org/wiki/Claudiu_T%C3%A2rziu
3,Emma Wiesner,NaN,Emma_Wiesner,https://en.wikipedia.org/wiki/Emma_Wiesner
4,Diana Șoșoacă,NaN,Diana_Șoșoacă,https://en.wikipedia.org/wiki/Diana_%C8%98o%C8...
...,...,...,...,...
743,Urmas Paet,http://urmaspaet.eu/,Urmas_Paet,https://en.wikipedia.org/wiki/Urmas_Paet
744,Villy Søvndal,NaN,Villy_Søvndal,https://en.wikipedia.org/wiki/Villy_S%C3%B8vndal
745,David McAllister,NaN,David_McAllister,https://en.wikipedia.org/wiki/David_McAllister
746,Thierry Mariani,https://www.mariani-2026.fr/,Thierry_Mariani,https://en.wikipedia.org/wiki/Thierry_Mariani
747,Q65437,https://www.bernd-lange.de,Bernd_Lange,https://en.wikipedia.org/wiki/Bernd_Lange

Let's do cleaning steps:

*Check for duplicates and remove them*

*Get insight into how many web adresses we have*

In [24]:
# Check for duplicates
print("Duplicate names:", df["name"].duplicated().sum())
print("Duplicate wiki titles:", df["wiki_title"].duplicated().sum())

Duplicate names: 15
Duplicate wiki titles: 15

In [25]:
df = df.drop_duplicates()

Check if we have an Wikipedia article and an official website for our politicians.

In [26]:
df.isna().sum()

name                  0
official_website    451
wiki_title            0
URL                   0
dtype: int64

## Fetch the actual full text articles

We can utilize `wikipediaapi` to get the full text of all the articles. For this we use the entries in `wiki_title` of our DataFrame.

To get the text of a wiki page we can use `Wikipedia.page(title)` and then `page.text`.

Save it in the DataFrame in the column `raw_text`.

We will limit the amount of politicians to 20, who have a website for this tutorial.

In [ ]:
df_with_website = df[df["official_website"].notna()].head(20).reset_index()

# Initialize the API
wiki = wikipediaapi.Wikipedia(user_agent=USER_AGENT, language='en')

full_texts = []

for i, title in tqdm(enumerate(df_with_website["wiki_title"], start=1), total=len(df_with_website["wiki_title"])):
    try:
        page = wiki.page(title)

        if page.exists():
            full_texts.append(page.text)
        else:
            print("no page?")
            full_texts.append(None)

        # You should not do too many requests at once
        time.sleep(0.3)

    except requests.HTTPError as e:
        print(e)
        full_texts.append(None)
        time.sleep(2)

    except Exception:
        print("error")
        full_texts.append(None)
        time.sleep(1)

df_with_website["raw_text"] = full_texts
display(df_with_website)

100%|██████████| 20/20 [00:12<00:00,  1.58it/s]

Done!

,index,name,official_website,wiki_title,URL,raw_text
0,8,Mario Mantovani,http://www.mariomantovani.it,Mario_Mantovani,https://en.wikipedia.org/wiki/Mario_Mantovani,"Mario Mantovani (born 28 July 1950, in Arconat..."
1,15,Aldo Patriciello,http://www.patriciello.it,Aldo_Patriciello,https://en.wikipedia.org/wiki/Aldo_Patriciello,Aldo Patriciello (born 27 September 1957 in Ve...
2,17,Christine Schneider,https://www.christine-schneider.de/,Christine_Schneider,https://en.wikipedia.org/wiki/Christine_Schneider,Christine Schneider (born 5 June 1972) is a Ge...
3,19,Birgit Sippel,http://www.birgitsippel.de,Birgit_Sippel,https://en.wikipedia.org/wiki/Birgit_Sippel,Birgit Sippel (born 29 January 1960) is a Germ...
4,27,Biljana Borzan,http://www.biljanaborzan.eu/hr/,Biljana_Borzan,https://en.wikipedia.org/wiki/Biljana_Borzan,Biljana Borzan (née Čupurdija; born 29 Novembe...
5,28,René Repasi,https://repasi.eu/,René_Repasi,https://en.wikipedia.org/wiki/Ren%C3%A9_Repasi,René Repasi (born 8 November 1979) is a German...
6,30,Maria Noichl,http://maria-noichl.eu/,Maria_Noichl,https://en.wikipedia.org/wiki/Maria_Noichl,Maria Noichl (born 9 January 1967) is a German...
7,32,Jan-Christoph Oetjen,https://janchristoph-oetjen.europa.fdp.de/,Jan-Christoph_Oetjen,https://en.wikipedia.org/wiki/Jan-Christoph_Oe...,Jan-Christoph Oetjen (born 21 February 1978 in...
8,36,Marina Mesure,https://marinamesure.fr,Marina_Mesure,https://en.wikipedia.org/wiki/Marina_Mesure,Marina Mesure (born 12 July 1989) is a French ...
9,40,Matthias Ecke,https://matthias-ecke.eu/,Matthias_Ecke,https://en.wikipedia.org/wiki/Matthias_Ecke,Matthias Ecke (born 12 April 1983) is a German...
10,42,Denis Nesci,https://www.denisnesci.it/,Denis_Nesci,https://en.wikipedia.org/wiki/Denis_Nesci,Denis Nesci (born 25 July 1981) is an Italian ...
11,44,Dainius Žalimas,https://dainiuszalimas.lt/,Dainius_Žalimas,https://en.wikipedia.org/wiki/Dainius_%C5%BDal...,Dainius Žalimas (born 22 May 1973) is a Lithua...
12,49,Krzysztof Hetman,http://krzysztofhetman.pl/en/,Krzysztof_Hetman,https://en.wikipedia.org/wiki/Krzysztof_Hetman,Krzysztof Andrzej Hetman (born 27 June 1974) i...
13,50,Marcin Kierwiński,https://kierwinski2024.pl,Marcin_Kierwiński,https://en.wikipedia.org/wiki/Marcin_Kierwi%C5...,Marcin Piotr Kierwiński (Polish pronunciation:...
14,51,Q11778705,https://dworczyk.pl,Michał_Dworczyk,https://en.wikipedia.org/wiki/Micha%C5%82_Dwor...,Michał Paweł Dworczyk (born 22 July 1975) is a...
15,53,Patryk Jaki,http://jaki.pl,Patryk_Jaki,https://en.wikipedia.org/wiki/Patryk_Jaki,Patryk Tomasz Jaki (born 11 May 1985) is a Pol...
16,54,Elsi Katainen,http://www.elsikatainen.fi,Elsi_Katainen,https://en.wikipedia.org/wiki/Elsi_Katainen,Elsi Kaarina Katainen (born 17 December 1966) ...
17,56,Veronika Vrecionová,https://vrecionova.cz,Veronika_Vrecionová,https://en.wikipedia.org/wiki/Veronika_Vrecion...,Veronika Vrecionová (born 8 September 1965) is...
18,59,Andrea Wechsler,https://andrea-wechsler.de/,Andrea_Wechsler,https://en.wikipedia.org/wiki/Andrea_Wechsler,Prof. Dr. Andrea Wechsler (born 19 June 1977) ...
19,60,Jan Farský,https://www.janfarsky.cz,Jan_Farský,https://en.wikipedia.org/wiki/Jan_Farsk%C3%BD,Jan Farský (born 11 July 1979) is a Czech poli...

We still see some section headers that we would like to avoid, e.g. References.

In [32]:
for i in range(3):
    print("=" * 80)
    print(df_with_website.loc[i, "name"])
    print(df_with_website.loc[i, "raw_text"][:2000])
    print()

================================================================================
Mario Mantovani
Mario Mantovani (born 28 July 1950, in Arconate) is an Italian politician. He has been Member of the European Parliament, a mayor, a senator, the Undersecretary for Infrastructure and Transport under Berlusconi, and Vice-President of the Lombardy Region.
In 2022, he was acquitted on appeal of corruption charges. In 2024, he was re-elected for a third mandate in the European Parliament, fifteen years after the end of his second mandate.
His daughter is the deputy of the Brothers of Italy Lucrezia Mantovani.

Early life and career
Mantovani graduated in foreign languages and literature in 1975. From 1981 to 1986 he was director of the Padre Beccaro Institute in Milan.
In 1990 he founded the Sodalitas non-profit organization, which in Bellaria-Igea Marina has a series of residences and summer camps.
In 1996 he opened the Mantovani Foundation, specialized in the construction and management of nursing homes for the elderly. With his appointment as undersecretary in 2008 he leaves the presidency of the Mantovani Foundation, leaving the guide to his family.
Mantovani owns the Immobiliare Vigevanese company, as well as the Mantovani Foundation. With the first he builds social welfare residences and with the second he manages four RSAs in the province of Milan which, added to those led by Sodalitas, make eleven structures and 830 beds, all accredited in the Lombardy region rankings. It also manages 13 day care centers for the disabled managed on behalf of the ASL of Milan 1.

Political activity
Member of the European Parliament
In 1999 he was elected MEP among the ranks of Forza Italia with 39,000 preferences and was re-elected in 2004 with 50,000 preferences. He sat in the European People's Party group. In 2008 he was elected to the Senate and left the seat in the European Parliament to Iva Zanicchi.

Mayor of Arconate
In 2001 he was also elected mayor of Arconate with 51% of the votes and was re-elected in 2006 with 68% of the votes. In November 2008, the municipal coun

================================================================================
Aldo Patriciello
Aldo Patriciello (born 27 September 1957 in Venafro) is an Italian politician.

A former Vice President of Molise, a region in southern Italy, he has been a member of the European Parliament since 8 May 2006, when he took the place of Lorenzo Cesa, elected to the Chamber of Deputies in the 2006 Italian general election. Having first run for the European Parliament in 2004, Patriciello was re-elected in 2009, 2014 and 2019.
Patriciello started his political career within Christian Democracy in 1979. After the party's dissolution in 1994, he successively joined the Italian People's Party, European Democracy, the Union of the Centre, Forza Italia, The People of Freedom, the new Forza Italia and, finally, since January 2024, Lega.
After being convicted to four months for illegal financing, Patriciello was never jailed.

References
External links
Personal profile of Aldo Patriciello in the European Parliament's database of members

================================================================================
Christine Schneider
Christine Schneider (born 5 June 1972) is a German carpenter and politician of the Christian Democratic Union (CDU) who has been serving as a Member of the European Parliament since 2019.

Political career
From 1996 to 2019, Schneider served as a member of the Landtag of Rhineland-Palatinate. In that capacity, she chaired the Committee on Agriculture from 2006 until 2016 and served as deputy chairwoman of her parliamentary group from 2016 until 2019, under the leadership of chairman Christian Baldauf.
Schneider has been a Member of the European Parliament since the 2019 European elections. She has since been serving on the Committee on the Environment, Public Health and Food Safety and the Committee on Women's Rights and Gender Equality. In addition to her committee assignments, she is part of the Parliament's Delegation for relations with South Africa.

Other activities
Sparkasse Südliche Weinstraße, Member of the Supervisory Board

References


== External links ==

## Text Cleaning

The text usually contains artifacts that we don't want as a description of politicians, e.g. `References`, `External Links`, `See also`, `further reading` and `notes`.

We also should remove trailing whitespaces and normalize whitespaces that contain multiple characters.

Clean the text and safe it in the column `clean_text`.

In [39]:
import re
import pandas as pd

def clean_wiki_text(text):
    if pd.isna(text) or text is None:
        return None

    text = str(text)

    # normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # These are section we want to remove
    stop_sections = {
        "references",
        "external links",
        "see also",
        "further reading",
        "notes",
    }

    cleaned_lines = []
    for line in text.split("\n"):
        line_stripped = line.strip().lower()

        # remove surrounding "=" so "== References ==" becomes "references"
        heading = line_stripped.replace("=", "").strip()

        if heading in stop_sections:
            break

        cleaned_lines.append(line)

    text = "\n".join(cleaned_lines)
    
    # collapse spaces and tabs
    text = re.sub(r"[ \t]+", " ", text)

    # remove spaces around newlines
    text = re.sub(r" *\n *", "\n", text)

    # collapse 3+ newlines to 2
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Remove trailing whitespaces
    text = text.strip()
    return text

df_with_website["clean_text"] = df_with_website["raw_text"].apply(clean_wiki_text)

In [41]:
for i in range(3):
    print("=" * 80)
    print(df_with_website.loc[i, "name"])
    print(df_with_website.loc[i, "clean_text"][:2000])
    print()

================================================================================
Mario Mantovani
Mario Mantovani (born 28 July 1950, in Arconate) is an Italian politician. He has been Member of the European Parliament, a mayor, a senator, the Undersecretary for Infrastructure and Transport under Berlusconi, and Vice-President of the Lombardy Region.
In 2022, he was acquitted on appeal of corruption charges. In 2024, he was re-elected for a third mandate in the European Parliament, fifteen years after the end of his second mandate.
His daughter is the deputy of the Brothers of Italy Lucrezia Mantovani.

Early life and career
Mantovani graduated in foreign languages and literature in 1975. From 1981 to 1986 he was director of the Padre Beccaro Institute in Milan.
In 1990 he founded the Sodalitas non-profit organization, which in Bellaria-Igea Marina has a series of residences and summer camps.
In 1996 he opened the Mantovani Foundation, specialized in the construction and management of nursing homes for the elderly. With his appointment as undersecretary in 2008 he leaves the presidency of the Mantovani Foundation, leaving the guide to his family.
Mantovani owns the Immobiliare Vigevanese company, as well as the Mantovani Foundation. With the first he builds social welfare residences and with the second he manages four RSAs in the province of Milan which, added to those led by Sodalitas, make eleven structures and 830 beds, all accredited in the Lombardy region rankings. It also manages 13 day care centers for the disabled managed on behalf of the ASL of Milan 1.

Political activity
Member of the European Parliament
In 1999 he was elected MEP among the ranks of Forza Italia with 39,000 preferences and was re-elected in 2004 with 50,000 preferences. He sat in the European People's Party group. In 2008 he was elected to the Senate and left the seat in the European Parliament to Iva Zanicchi.

Mayor of Arconate
In 2001 he was also elected mayor of Arconate with 51% of the votes and was re-elected in 2006 with 68% of the votes. In November 2008, the municipal council

================================================================================
Aldo Patriciello
Aldo Patriciello (born 27 September 1957 in Venafro) is an Italian politician.

A former Vice President of Molise, a region in southern Italy, he has been a member of the European Parliament since 8 May 2006, when he took the place of Lorenzo Cesa, elected to the Chamber of Deputies in the 2006 Italian general election. Having first run for the European Parliament in 2004, Patriciello was re-elected in 2009, 2014 and 2019.
Patriciello started his political career within Christian Democracy in 1979. After the party's dissolution in 1994, he successively joined the Italian People's Party, European Democracy, the Union of the Centre, Forza Italia, The People of Freedom, the new Forza Italia and, finally, since January 2024, Lega.
After being convicted to four months for illegal financing, Patriciello was never jailed.

================================================================================
Christine Schneider
Christine Schneider (born 5 June 1972) is a German carpenter and politician of the Christian Democratic Union (CDU) who has been serving as a Member of the European Parliament since 2019.

Political career
From 1996 to 2019, Schneider served as a member of the Landtag of Rhineland-Palatinate. In that capacity, she chaired the Committee on Agriculture from 2006 until 2016 and served as deputy chairwoman of her parliamentary group from 2016 until 2019, under the leadership of chairman Christian Baldauf.
Schneider has been a Member of the European Parliament since the 2019 European elections. She has since been serving on the Committee on the Environment, Public Health and Food Safety and the Committee on Women's Rights and Gender Equality. In addition to her committee assignments, she is part of the Parliament's Delegation for relations with South Africa.

Other activities
Sparkasse Südliche Weinstraße, Member of the Supervisory Board

## Find social media accounts on the official websites

We can use beautifulsoup and requests to find social media links on the official websites of the MEP.

Implement a method that takes the url and returns a dictionary with the `youtube`, `instagram`, `x_com` and `facebook` account of the politician.

In [42]:
def find_social_links(website_url):
    result = {
        "youtube": None,
        "instagram": None,
        "x_com": None,
        "facebook": None,
    }

    if website_url is None:
        return result

    website_url = str(website_url).strip()
    if website_url == "" or website_url.lower() == "nan":
        return result

    try:
        response = requests.get(website_url, headers=headers, timeout=15)
        response.raise_for_status()
    except Exception:
        return result

    soup = BeautifulSoup(response.text, "html.parser")

    for a in soup.find_all("a", href=True):
        href = a.get("href", "").strip()
        if not href:
            continue

        href = urljoin(response.url, href)
        domain = urlparse(href).netloc.lower()

        if result["youtube"] is None and ("youtube.com" in domain or "youtu.be" in domain):
            result["youtube"] = href
        elif result["instagram"] is None and "instagram.com" in domain:
            result["instagram"] = href
        elif result["x_com"] is None and ("x.com" in domain or "twitter.com" in domain):
            result["x_com"] = href
        elif result["facebook"] is None and ("facebook.com" in domain or "fb.me" in domain):
            result["facebook"] = href

    return result

In [44]:
df_with_website[["youtube", "instagram", "x_com", "facebook"]] = (
    df_with_website["official_website"]
    .apply(find_social_links)
    .apply(pd.Series)
)

In [45]:
df_with_website

,index,name,official_website,wiki_title,URL,raw_text,clean_text,youtube,instagram,x_com,facebook
0,8,Mario Mantovani,http://www.mariomantovani.it,Mario_Mantovani,https://en.wikipedia.org/wiki/Mario_Mantovani,"Mario Mantovani (born 28 July 1950, in Arconat...","Mario Mantovani (born 28 July 1950, in Arconat...",NaN,NaN,NaN,NaN
1,15,Aldo Patriciello,http://www.patriciello.it,Aldo_Patriciello,https://en.wikipedia.org/wiki/Aldo_Patriciello,Aldo Patriciello (born 27 September 1957 in Ve...,Aldo Patriciello (born 27 September 1957 in Ve...,https://www.youtube.com/user/apatriciello,https://www.instagram.com/aldopatriciello_offi...,https://twitter.com/PatricielloAldo,https://www.facebook.com/AldoPatriciello
2,17,Christine Schneider,https://www.christine-schneider.de/,Christine_Schneider,https://en.wikipedia.org/wiki/Christine_Schneider,Christine Schneider (born 5 June 1972) is a Ge...,Christine Schneider (born 5 June 1972) is a Ge...,NaN,https://www.instagram.com/christineschneider_m...,NaN,https://www.facebook.com/christine.schneider.m...
3,19,Birgit Sippel,http://www.birgitsippel.de,Birgit_Sippel,https://en.wikipedia.org/wiki/Birgit_Sippel,Birgit Sippel (born 29 January 1960) is a Germ...,Birgit Sippel (born 29 January 1960) is a Germ...,https://www.youtube.com/user/birgitsippel,https://www.instagram.com/birgit_sippel/,https://twitter.com/BirgitSippelMEP,https://www.facebook.com/BirgitSippel
4,27,Biljana Borzan,http://www.biljanaborzan.eu/hr/,Biljana_Borzan,https://en.wikipedia.org/wiki/Biljana_Borzan,Biljana Borzan (née Čupurdija; born 29 Novembe...,Biljana Borzan (née Čupurdija; born 29 Novembe...,NaN,NaN,NaN,NaN
5,28,René Repasi,https://repasi.eu/,René_Repasi,https://en.wikipedia.org/wiki/Ren%C3%A9_Repasi,René Repasi (born 8 November 1979) is a German...,René Repasi (born 8 November 1979) is a German...,https://www.youtube.com/channel/UCYSfk8Sh3CCek...,https://www.instagram.com/rene.repasi/,https://twitter.com/repasi,https://www.facebook.com/repasi
6,30,Maria Noichl,http://maria-noichl.eu/,Maria_Noichl,https://en.wikipedia.org/wiki/Maria_Noichl,Maria Noichl (born 9 January 1967) is a German...,Maria Noichl (born 9 January 1967) is a German...,https://youtu.be/AgCIw7Oj5h0,NaN,https://twitter.com/marianoichl,https://www.facebook.com/noichl.eu
7,32,Jan-Christoph Oetjen,https://janchristoph-oetjen.europa.fdp.de/,Jan-Christoph_Oetjen,https://en.wikipedia.org/wiki/Jan-Christoph_Oe...,Jan-Christoph Oetjen (born 21 February 1978 in...,Jan-Christoph Oetjen (born 21 February 1978 in...,NaN,NaN,NaN,NaN
8,36,Marina Mesure,https://marinamesure.fr,Marina_Mesure,https://en.wikipedia.org/wiki/Marina_Mesure,Marina Mesure (born 12 July 1989) is a French ...,Marina Mesure (born 12 July 1989) is a French ...,https://www.youtube.com/@marina.mesure,https://www.instagram.com/marina.mesure/,https://twitter.com/MarinaMesure,https://www.facebook.com/MarinaMesureFi
9,40,Matthias Ecke,https://matthias-ecke.eu/,Matthias_Ecke,https://en.wikipedia.org/wiki/Matthias_Ecke,Matthias Ecke (born 12 April 1983) is a German...,Matthias Ecke (born 12 April 1983) is a German...,NaN,https://www.instagram.com/matthias.ecke/,https://twitter.com/MattEcke,https://www.facebook.com/matthiasecke
10,42,Denis Nesci,https://www.denisnesci.it/,Denis_Nesci,https://en.wikipedia.org/wiki/Denis_Nesci,Denis Nesci (born 25 July 1981) is an Italian ...,Denis Nesci (born 25 July 1981) is an Italian ...,https://www.youtube.com/@on.denisnesci,https://www.instagram.com/denis_nesci,https://twitter.com/denisnesci,https://www.facebook.com/denisnesciofficial
11,44,Dainius Žalimas,https://dainiuszalimas.lt/,Dainius_Žalimas,https://en.wikipedia.org/wiki/Dainius_%C5%BDal...,Dainius Žalimas (born 22 May 1973) is a Lithua...,Dainius Žalimas (born 22 May 1973) is a Lithua...,NaN,https://www.instagram.com/teisingasvisiems/,NaN,https://www.facebook.com/epzalimas
12,49,Krzysztof Hetman,http://krzysztofhetman.pl/en/,Krzysztof_Hetman,https://en.wikipedia.org/wiki/Krzysztof_Hetman,Krzysztof Andrzej Hetman (born 27 June 1974) i...,Krzysztof Andrzej Hetman (born 27 June 1974) i...,NaN,NaN,NaN,NaN
13,50,Marcin Kierwiński,https://kierwinski2024.pl,Marcin_Kierwiński,https://en.wikipedia.org/wiki/Marcin_Kierwi%C5...,Marcin Piotr Kierwiński (Polish pronunciation:...,Marcin Piotr Kierwiński (Polish pronunciation:...,NaN,NaN,NaN,NaN
14,51,Q11778705,https://dworczyk.pl,Michał_Dworczyk,https://en.wikipedia.org/wiki/Micha%C5%82_Dwor...,Michał Paweł Dworczyk (born 22 July 1975) is a...,Michał Paweł Dworczyk (born 22 July 1975) is a...,https://www.youtube.com/@MichalDworczykpl/shorts,NaN,https://x.com/michaldworczyk,https://www.facebook.com/DworczykMichal
15,53,Patryk Jaki,http://jaki.pl,Patryk_Jaki,https://en.wikipedia.org/wiki/Patryk_Jaki,Patryk Tomasz Jaki (born 11 May 1985) is a Pol...,Patryk Tomasz Jaki (born 11 May 1985) is a Pol...,https://www.youtube.com/patrykjakipl,https://www.instagram.com/patrykjaki_official/,https://twitter.com/PatrykJaki,https://www.facebook.com/PatrykJaki/
16,54,Elsi Katainen,http://www.elsikatainen.fi,Elsi_Katainen,https://en.wikipedia.org/wiki/Elsi_Katainen,Elsi Kaarina Katainen (born 17 December 1966) ...,Elsi Kaarina Katainen (born 17 December 1966) ...,NaN,https://www.instagram.com/elsikatainen/,https://twitter.com/ElsiKatainen,https://facebook.com/elsi.katainen
17,56,Veronika Vrecionová,https://vrecionova.cz,Veronika_Vrecionová,https://en.wikipedia.org/wiki/Veronika_Vrecion...,Veronika Vrecionová (born 8 September 1965) is...,Veronika Vrecionová (born 8 September 1965) is...,NaN,https://www.instagram.com/veronikavrecionova,https://twitter.com/vrecionova,https://www.facebook.com/veronika.vrecionova
18,59,Andrea Wechsler,https://andrea-wechsler.de/,Andrea_Wechsler,https://en.wikipedia.org/wiki/Andrea_Wechsler,Prof. Dr. Andrea Wechsler (born 19 June 1977) ...,Prof. Dr. Andrea Wechsler (born 19 June 1977) ...,https://www.youtube.com/@EUundDU,https://www.instagram.com/wechsler_andrea,https://twitter.com/andreawechsler,https://www.facebook.com/andrea.wechsler.cdu
19,60,Jan Farský,https://www.janfarsky.cz,Jan_Farský,https://en.wikipedia.org/wiki/Jan_Farsk%C3%BD,Jan Farský (born 11 July 1979) is a Czech poli...,Jan Farský (born 11 July 1979) is a Czech poli...,NaN,https://www.instagram.com/jan_farsky/,https://x.com/JanFar_sky?ref_src=twsrc%5Egoogl...,https://www.facebook.com/farskyjansemily

In [47]:
df_with_website.isna().sum()

index                0
name                 0
official_website     0
wiki_title           0
URL                  0
raw_text             0
clean_text           0
youtube             11
instagram            7
x_com                7
facebook             5
dtype: int64